# Generated by Django 4.2.30 on 2026-04-30 03:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tributario_app', '0057_fix_pagovariostemp_id_autoincrement_postgres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuyente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtn', models.CharField(blank=True, max_length=20, null=True, verbose_name='RTN')),
                ('direccion_notificacion', models.TextField(blank=True, null=True, verbose_name='Dirección de Notificación')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contribuyente_personal', to='tributario_app.identificacion')),
            ],
            options={
                'verbose_name': 'Contribuyente Personal',
                'verbose_name_plural': 'Contribuyentes Personales',
            },
        ),
        migrations.CreateModel(
            name='TarifasPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Año Fiscal')),
                ('desde', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Rango Desde')),
                ('hasta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Rango Hasta')),
                ('tasa', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa (Millar)')),
                ('valor_fijo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Fijo')),
            ],
            options={
                'verbose_name': 'Tarifa Impuesto Personal',
                'verbose_name_plural': 'Tarifas Impuesto Personal',
                'ordering': ['ano', 'desde'],
            },
        ),
        migrations.CreateModel(
            name='PlanillaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('archivo', models.FileField(upload_to='planillas/', verbose_name='Archivo de Planilla')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tributario_app.negocio', verbose_name='Empresa/Negocio')),
            ],
            options={
                'verbose_name': 'Planilla de Empresa',
                'verbose_name_plural': 'Planillas de Empresas',
            },
        ),
        migrations.CreateModel(
            name='DetallePlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidad', models.CharField(max_length=20, verbose_name='Identidad del Empleado')),
                ('nombre_empleado', models.CharField(max_length=150, verbose_name='Nombre')),
                ('sueldo_bruto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sueldo Bruto')),
                ('impuesto_retenido', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Impuesto Retenido')),
                ('planilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='impuesto_personal.planillaempresa')),
            ],
            options={
                'verbose_name': 'Detalle de Planilla',
                'verbose_name_plural': 'Detalles de Planillas',
            },
        ),
        migrations.CreateModel(
            name='DeclaracionPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_fiscal', models.IntegerField(verbose_name='Año Fiscal')),
                ('fecha_presentacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Presentación')),
                ('renta_bruta', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Renta Bruta Anual')),
                ('deducciones', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Deducciones')),
                ('renta_neta', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Renta Neta Gravable')),
                ('impuesto_calculado', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Impuesto Calculado')),
                ('multa', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Multa por Presentación Tardía')),
                ('recargo', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Recargos/Intereses')),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Total a Pagar')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('presentada', 'Presentada'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('usuario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario que registró')),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declaraciones', to='impuesto_personal.contribuyente')),
            ],
            options={
                'verbose_name': 'Declaración Personal',
                'verbose_name_plural': 'Declaraciones Personales',
                'unique_together': {('contribuyente', 'ano_fiscal')},
            },
        ),
    ]
