import psycopg

SUPABASE_URL = "postgresql://postgres.inzasugoozqqnelcvrwd:Sandres0318$$@aws-1-us-west-2.pooler.supabase.com:6543/postgres"

def fix_schema():
    tables = ['mod_usuarios_usuario', 'mod_usuarios_acceso_modulo', 'mod_usuarios_perfil', 'mod_usuarios_permiso', 'mod_usuarios_rol', 'mod_usuarios_usuario_rol']
    
    try:
        with psycopg.connect(SUPABASE_URL) as conn:
            with conn.cursor() as cur:
                print("--- Fixing User Schema ---")
                for table in tables:
                    print(f"Processing {table}...", end="")
                    # 1. Add identity if missing
                    # We use a TRY...CATCH block in SQL to avoid errors if already identity
                    cur.execute(f"DO $$ BEGIN PERFORM 1 FROM pg_attribute WHERE attrelid = '\"{table}\"'::regclass AND attname = 'id' AND attidentity = ''; IF FOUND THEN ALTER TABLE \"{table}\" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY; END IF; END $$;")
                    
                    # 2. Reset sequence to max(id) + 1
                    cur.execute(f"SELECT COALESCE(MAX(id), 0) + 1 FROM \"{table}\"")
                    next_id = cur.fetchone()[0]
                    cur.execute(f"ALTER TABLE \"{table}\" ALTER COLUMN id RESTART WITH {next_id}")
                    print(f" [Restarted at {next_id}]")
                conn.commit()
        print("\nSchema Fix Completed.")
    except Exception as e:
        print(f"\nError: {e}")

if __name__ == "__main__":
    fix_schema()
