# Generated by Django 4.2.27 on 2026-04-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_remove_departamento_from_configuracion_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caserio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('depto', models.CharField(db_collation='latin1_spanish_ci', max_length=3, verbose_name='Departamento')),
                ('codmuni', models.CharField(db_collation='latin1_swedish_ci', max_length=3, verbose_name='Código Municipio')),
                ('codbarrio', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=3, verbose_name='Código Barrio')),
                ('codigo', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=3, verbose_name='Código Caserío')),
                ('descripcion', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=50, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Caserío',
                'verbose_name_plural': 'Caseríos',
                'db_table': 'caserio',
                'ordering': ['depto', 'codmuni', 'codbarrio', 'codigo'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(db_collation='latin1_swedish_ci', max_length=3, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(db_collation='latin1_swedish_ci', max_length=45, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
                'db_table': 'nacionalidad',
                'ordering': ['codigo'],
                'managed': False,
            },
        ),
    ]
