# Generated by Django 4.2.27 on 2026-04-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_catalogos_unmanaged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Sitio del predio',
                'verbose_name_plural': 'Sitios del predio',
                'db_table': 'sitio',
                'ordering': ['codigo'],
            },
        ),
    ]
