# Generated by Django 4.2.27 on 2026-04-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_sitio'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.CreateModel(
            name='Agua',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Agua',
                'verbose_name_plural': 'Agua',
                'db_table': 'agua',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Alumbrado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Alumbrado',
                'verbose_name_plural': 'Alumbrado',
                'db_table': 'alumbrado',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Calle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Calle',
                'verbose_name_plural': 'Calles',
                'db_table': 'calle',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Colindancias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Colindancias',
                'verbose_name_plural': 'Colindancias',
                'db_table': 'colindancias',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de dominio',
                'verbose_name_plural': 'Tipos de dominio',
                'db_table': 'dominio',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Drenaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de alcantarillado',
                'verbose_name_plural': 'Tipos de alcantarillado',
                'db_table': 'drenaje',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Electricidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Electricidad',
                'verbose_name_plural': 'Electricidad',
                'db_table': 'electricidad',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Explotacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Explotación del predio',
                'verbose_name_plural': 'Explotación del predio',
                'db_table': 'explotacion',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Habitacional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Código habitacional',
                'verbose_name_plural': 'Códigos habitacionales',
                'db_table': 'habitacional',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Irrigacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Sistema de irrigación',
                'verbose_name_plural': 'Sistemas de irrigación',
                'db_table': 'irrigacion',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Naturaleza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Naturaleza jurídica',
                'verbose_name_plural': 'Naturalezas jurídicas',
                'db_table': 'naturaleza',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Subuso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Sub uso del predio',
                'verbose_name_plural': 'Sub usos del predio',
                'db_table': 'subuso',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Teléfono',
                'verbose_name_plural': 'Teléfono',
                'db_table': 'telefono',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Tipomedida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de medida',
                'verbose_name_plural': 'Tipos de medida',
                'db_table': 'tipomedida',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Topografia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Topografía del predio',
                'verbose_name_plural': 'Topografías del predio',
                'db_table': 'topografia',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Usotierra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Uso de tierra',
                'verbose_name_plural': 'Usos de tierra',
                'db_table': 'usotierra',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Vias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Vías de comunicación',
                'verbose_name_plural': 'Vías de comunicación',
                'db_table': 'vias',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Zonasusos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Zonificación',
                'verbose_name_plural': 'Zonificaciones',
                'db_table': 'zonasusos',
                'managed': False,
                'ordering': ['codigo'],
            },
        ),
            ],
            database_operations=[],
        ),
    ]
