# Generated by Django 4.2.30 on 2026-04-30 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0006_cfg_subuso_topografia_rename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cfgsubuso',
            options={'managed': False, 'ordering': ['uso', 'codsubuso'], 'verbose_name': 'Uso del predio', 'verbose_name_plural': 'Usos del predio'},
        ),
    ]
