# Generated by Django 4.2.27 on 2026-03-22 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('presupuestos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentapresupuestaria',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cuentapresupuestaria',
            name='cuenta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='presupuestos.cuentapresupuestaria', verbose_name='Cuenta padre'),
        ),
        migrations.AddField(
            model_name='cuentapresupuestaria',
            name='nivel',
            field=models.IntegerField(default=1, verbose_name='Nivel jerárquico'),
        ),
        migrations.AddField(
            model_name='cuentapresupuestaria',
            name='tipo_cuenta',
            field=models.CharField(choices=[('TITULO', 'Título/Agrupadora'), ('DETALLE', 'Detalle/Movimiento')], default='DETALLE', max_length=10, verbose_name='Tipo Cuenta'),
        ),
        migrations.AddField(
            model_name='cuentapresupuestaria',
            name='tipo_presupuesto',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], default='EGRESO', max_length=10, verbose_name='Tipo Presupuesto'),
        ),
        migrations.AlterField(
            model_name='cuentapresupuestaria',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_presupuestarias', to='contabilidad.cuentacontable', verbose_name='Cuenta contable'),
        ),
        migrations.CreateModel(
            name='ReformaPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.CharField(max_length=10, verbose_name='Empresa/Municipio')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('AMPLIACION', 'Ampliación (+)'), ('REDUCCION', 'Reducción (-)'), ('TRASPASO', 'Traspaso (+/-)')], max_length=20)),
                ('referencia', models.CharField(max_length=100, verbose_name='No. Documento/Referencia')),
                ('concepto', models.TextField(verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reformas_destino', to='presupuestos.cuentapresupuestaria', verbose_name='Cuenta Destino/Afectada')),
                ('cuenta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reformas_origen', to='presupuestos.cuentapresupuestaria', verbose_name='Cuenta Origen (solo para traspasos)')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reformas', to='contabilidad.ejerciciofiscal')),
                ('fondo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reformas', to='presupuestos.fondo', verbose_name='Fondo afectado')),
            ],
            options={
                'verbose_name': 'Reforma Presupuestaria',
                'verbose_name_plural': 'Reformas Presupuestarias',
                'db_table': 'presu_reforma',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.CharField(max_length=10, verbose_name='Empresa/Municipio')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto inicial/Aprobado')),
                ('monto_reformas', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Reformas/Modificaciones')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_anuales', to='presupuestos.cuentapresupuestaria', verbose_name='Cuenta presupuestaria')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_anuales', to='contabilidad.ejerciciofiscal', verbose_name='Ejercicio fiscal')),
                ('fondo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos_anuales', to='presupuestos.fondo', verbose_name='Fondo de financiamiento')),
            ],
            options={
                'verbose_name': 'Presupuesto Anual',
                'verbose_name_plural': 'Presupuestos Anuales',
                'db_table': 'presu_anual',
                'ordering': ['cuenta__codigo'],
                'unique_together': {('empresa', 'ejercicio', 'cuenta', 'fondo')},
            },
        ),
    ]
