# Generated by Django 4.2.27 on 2026-03-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0003_populate_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='reformapresupuestaria',
            name='punto_acta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Punto de Acta / Resolución'),
        ),
    ]
