# Generated by Django 4.2.27 on 2026-03-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_reformapresupuestaria_punto_acta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenpago',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador/Preparación'), ('APROBADA', 'Aprobada/Lista para Pago'), ('PAGADA', 'Pagada (Tesorería)'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=10),
        ),
    ]
