# Generated by Django 4.2.27 on 2026-03-22 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('presupuestos', '0005_alter_ordenpago_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.CharField(max_length=10, verbose_name='Empresa/Municipio')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('beneficiario', models.CharField(max_length=200, verbose_name='Beneficiario')),
                ('concepto', models.TextField(verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cuenta', models.ForeignKey(limit_choices_to={'tipo_presupuesto': 'EGRESO'}, on_delete=django.db.models.deletion.PROTECT, to='presupuestos.cuentapresupuestaria')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_manuales', to='contabilidad.ejerciciofiscal')),
                ('fondo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_manuales', to='presupuestos.fondo')),
            ],
            options={
                'verbose_name': 'Gasto Manual',
                'verbose_name_plural': 'Gastos Manuales',
                'db_table': 'presu_gasto_manual',
            },
        ),
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.CharField(max_length=10, verbose_name='Empresa/Municipio')),
                ('numero', models.CharField(max_length=30, verbose_name='Número de Reserva')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('favorecido', models.CharField(max_length=200, verbose_name='Favorecido/Proveedor')),
                ('concepto', models.TextField(verbose_name='Concepto de la Reserva')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador/Preparación'), ('COMPROMETIDO', 'Comprometido/Reserva'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=15)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='contabilidad.ejerciciofiscal')),
                ('fondo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compromisos', to='presupuestos.fondo')),
            ],
            options={
                'verbose_name': 'Compromiso/Reserva de Fondo',
                'verbose_name_plural': 'Compromisos/Reservas de Fondo',
                'db_table': 'presu_compromiso',
                'unique_together': {('empresa', 'ejercicio', 'numero')},
            },
        ),
    ]
