# Generated by Django 4.2.27 on 2026-03-22 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('presupuestos', '0006_gastomanual_compromiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.CharField(max_length=10, verbose_name='Empresa/Municipio')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], default='EGRESO', max_length=10)),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('beneficiario', models.CharField(max_length=200, verbose_name='Beneficiario')),
                ('concepto', models.TextField(verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuestos.cuentapresupuestaria')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_manuales', to='contabilidad.ejerciciofiscal')),
                ('fondo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_manuales', to='presupuestos.fondo')),
            ],
            options={
                'verbose_name': 'Operación Manual',
                'verbose_name_plural': 'Operaciones Manuales',
                'db_table': 'presu_operacion_manual',
            },
        ),
        migrations.DeleteModel(
            name='GastoManual',
        ),
    ]
