# Generated by Django 4.2.30 on 2026-04-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0011_rendicionforma06captura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendicionforma07ajuste',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='rendicionforma07ajuste',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='rendicionforma07ajuste',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
