# Generated by Django 4.2.30 on 2026-04-30 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_tipoinventario_catalogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'ordering': ['tipo_inventario__orden', 'tipo_inventario__nombre', 'codigo'], 'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventarios'},
        ),
        migrations.AlterField(
            model_name='ejerciciofiscal',
            name='anio',
            field=models.IntegerField(verbose_name='Año fiscal'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código interno'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cuenta_costo_venta',
            field=models.ForeignKey(help_text='Segunda vinculación al mismo plan de cuentas: cuenta de gasto o de costo que se usa cuando el bien sale de inventario (venta, consumo interno, donación, merma o baja), para registrar el costo asociado (por ejemplo costo de ventas, consumo de materiales o gasto por servicios, según el caso). La cuenta concreta la define su ente y su manual contable; también debe existir en el catálogo contable.', on_delete=django.db.models.deletion.PROTECT, related_name='costos_venta', to='contabilidad.cuentacontable', verbose_name='Cuenta de costo de venta / consumo'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='cuenta_inventario',
            field=models.ForeignKey(help_text='Vinculación con el plan de cuentas (catálogo contable de su empresa): cuenta de activo donde se reconoce el valor del stock de este ítem (existencias a costo o al menor entre costo y valor neto realizable, según NIC 2). Debe ser una cuenta de detalle que acepte movimientos, en la rama de inventarios o materiales. Solo puede elegir cuentas ya dadas de alta en Contabilidad → Plan de cuentas.', on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='contabilidad.cuentacontable', verbose_name='Cuenta de inventario'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='tipo_inventario',
            field=models.ForeignKey(blank=True, help_text='Definido en el catálogo por empresa (configuración de tipos).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='contabilidad.tipoinventario', verbose_name='Tipo de inventario'),
        ),
        migrations.AlterField(
            model_name='tipoinventario',
            name='nombre',
            field=models.CharField(help_text='Ej. Químicos para tratamiento, Repuestos de bombeo, Suministros de oficina.', max_length=120, verbose_name='Nombre del tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='ejerciciofiscal',
            unique_together={('anio', 'empresa')},
        ),
    ]
