# Generated by Django 5.2.1 on 2025-08-13 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablecimientoComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo_establecimiento', models.CharField(max_length=50, unique=True, verbose_name='Código del Establecimiento')),
                ('nombre_comercial', models.CharField(max_length=200, verbose_name='Nombre Comercial')),
                ('propietario', models.CharField(max_length=200, verbose_name='Propietario')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('actividad_comercial', models.CharField(max_length=200, verbose_name='Actividad Comercial')),
                ('area_establecimiento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área del Establecimiento (m²)')),
                ('valor_establecimiento', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor del Establecimiento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Establecimiento Comercial',
                'verbose_name_plural': 'Establecimientos Comerciales',
                'db_table': 'mod_catastro_establecimiento_comercial',
                'ordering': ['codigo_establecimiento'],
            },
        ),
        migrations.CreateModel(
            name='PropiedadInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo_catastral', models.CharField(max_length=50, unique=True, verbose_name='Código Catastral')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('propietario', models.CharField(max_length=200, verbose_name='Propietario')),
                ('area_terreno', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área del Terreno (m²)')),
                ('area_construccion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Área de Construcción (m²)')),
                ('valor_catastral', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Catastral')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Propiedad Inmueble',
                'verbose_name_plural': 'Propiedades Inmuebles',
                'db_table': 'mod_catastro_propiedad_inmueble',
                'ordering': ['codigo_catastral'],
            },
        ),
        migrations.CreateModel(
            name='Construccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo_construccion', models.CharField(max_length=100, verbose_name='Tipo de Construcción')),
                ('area_construccion', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área de Construcción (m²)')),
                ('numero_pisos', models.IntegerField(default=1, verbose_name='Número de Pisos')),
                ('material_construccion', models.CharField(max_length=100, verbose_name='Material de Construcción')),
                ('valor_construccion', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor de Construcción')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio', verbose_name='Municipio')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.propiedadinmueble', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Construcción',
                'verbose_name_plural': 'Construcciones',
                'db_table': 'mod_catastro_construccion',
                'ordering': ['propiedad__codigo_catastral'],
            },
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo_terreno', models.CharField(max_length=50, unique=True, verbose_name='Código del Terreno')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área (m²)')),
                ('tipo_terreno', models.CharField(max_length=100, verbose_name='Tipo de Terreno')),
                ('uso_terreno', models.CharField(max_length=100, verbose_name='Uso del Terreno')),
                ('valor_terreno', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor del Terreno')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Terreno',
                'verbose_name_plural': 'Terrenos',
                'db_table': 'mod_catastro_terreno',
                'ordering': ['codigo_terreno'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('propietario', models.CharField(max_length=200, verbose_name='Propietario')),
                ('valor_vehiculo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor del Vehículo')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'mod_catastro_vehiculo',
                'ordering': ['placa'],
            },
        ),
    ]
