# Generated by Django 5.2.1 on 2025-08-15 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='departamento',
            new_name='departament_codigo_d7e7cf_idx',
            old_name='departamento_codigo_idx',
        ),
    ]
