# Generated by Django 5.2.1 on 2025-10-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo_app', '0002_rename_departamento_codigo_idx_departament_codigo_d7e7cf_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
