# Generated by Django 4.2.27 on 2026-04-04 18:17

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(db_index=True, max_length=10, verbose_name='Empresa/Municipio')),
                ('numero', models.CharField(max_length=80, verbose_name='Número de contrato / orden')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('monto_estimado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Monto estimado')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('vigente', 'Vigente'), ('vencido', 'Vencido'), ('anulado', 'Anulado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Contrato administrativo',
                'verbose_name_plural': 'Contratos administrativos',
                'db_table': 'adm_contrato',
                'ordering': ['-fecha_inicio', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ExpedienteGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(db_index=True, max_length=10, verbose_name='Empresa/Municipio')),
                ('codigo_interno', models.CharField(max_length=40, verbose_name='Código interno')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('compras', 'Compras'), ('contratacion', 'Contratación'), ('general', 'General'), ('otro', 'Otro')], default='general', max_length=20, verbose_name='Tipo')),
                ('fecha_apertura', models.DateField(verbose_name='Fecha de apertura')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_tramite', 'En trámite'), ('cerrado', 'Cerrado'), ('archivado', 'Archivado')], default='abierto', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Expediente de gestión',
                'verbose_name_plural': 'Expedientes de gestión',
                'db_table': 'adm_expediente',
                'ordering': ['-fecha_apertura', 'codigo_interno'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(db_index=True, max_length=10, verbose_name='Empresa/Municipio')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón social / nombre')),
                ('nit', models.CharField(blank=True, default='', max_length=20, verbose_name='NIT / identificación')),
                ('telefono', models.CharField(blank=True, default='', max_length=40, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Correo')),
                ('direccion', models.CharField(blank=True, default='', max_length=255, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'adm_proveedor',
                'ordering': ['razon_social'],
            },
        ),
        # No eliminar la tabla `departamento` en BD: la usa `core.Departamento`. Solo se retira del estado de esta app.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='Departamento'),
            ],
            database_operations=[],
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['empresa', 'razon_social'], name='adm_proveed_empresa_27bf47_idx'),
        ),
        migrations.AddIndex(
            model_name='expedientegestion',
            index=models.Index(fields=['empresa', 'estado'], name='adm_expedie_empresa_cfa385_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expedientegestion',
            unique_together={('empresa', 'codigo_interno')},
        ),
        migrations.AddField(
            model_name='contratoadministrativo',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='administrativo_main.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddIndex(
            model_name='contratoadministrativo',
            index=models.Index(fields=['empresa', 'estado'], name='adm_contrat_empresa_7908b2_idx'),
        ),
    ]
