# Generated by Django 4.2.27 on 2026-04-05 17:41

import administrativo.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo_main', '0005_proveedor_documentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='documentacion',
            field=models.FileField(blank=True, help_text='PDF u ofimática. El archivo se guarda en carpeta exclusiva del municipio en sesión.', null=True, upload_to=administrativo.models.proveedor_documentacion_upload_to, validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg', 'doc', 'docx'])], verbose_name='Documentación digital'),
        ),
    ]
