# Generated by Django 4.2.27 on 2026-04-08 04:21

from django.db import migrations, models
import servicios_publicos.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_publicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splectura',
            name='foto_medidor',
            field=models.FileField(blank=True, null=True, upload_to=servicios_publicos.models.foto_medidor_path, verbose_name='Foto del medidor'),
        ),
    ]
