-- MIGRATION 0001
BEGIN;
--
-- Create model ActivoFijo
--
CREATE TABLE "cont_activo_fijo" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "codigo" varchar(20) NOT NULL, "descripcion" varchar(500) NOT NULL, "fecha_adquisicion" date NOT NULL, "costo_adquisicion" numeric(18, 2) NOT NULL, "valor_residual" numeric(18, 2) NOT NULL, "vida_util_meses" integer NOT NULL, "metodo_depreciacion" varchar(30) NOT NULL, "depreciacion_acumulada" numeric(18, 2) NOT NULL, "valor_en_libros" numeric(18, 2) NOT NULL, "ubicacion" varchar(200) NULL, "responsable" varchar(200) NULL, "numero_serie" varchar(100) NULL, "estado" varchar(20) NOT NULL, "empresa" varchar(10) NOT NULL);
--
-- Create model ActivoIntangible
--
CREATE TABLE "cont_activo_intangible" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "codigo" varchar(20) NOT NULL, "descripcion" varchar(500) NOT NULL, "tipo_vida" varchar(20) NOT NULL, "costo_adquisicion" numeric(18, 2) NOT NULL, "amortizacion_acumulada" numeric(18, 2) NOT NULL, "vida_util_meses" integer NULL, "fecha_adquisicion" date NOT NULL, "empresa" varchar(10) NOT NULL);
--
-- Create model AsientoContable
--
CREATE TABLE "cont_asiento_contable" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "numero" varchar(20) NOT NULL, "fecha" date NOT NULL, "concepto" text NOT NULL, "referencia" varchar(100) NULL, "documento" varchar(50) NULL, "tasa_cambio" numeric(18, 6) NOT NULL, "total_debe" numeric(18, 2) NOT NULL, "total_haber" numeric(18, 2) NOT NULL, "estado" varchar(20) NOT NULL, "empresa" varchar(10) NOT NULL, "aprobado_por" varchar(100) NULL, "fecha_aprobacion" timestamp with time zone NULL);
--
-- Create model CentroCosto
--
CREATE TABLE "cont_centro_costo" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "codigo" varchar(20) NOT NULL, "nombre" varchar(200) NOT NULL, "responsable" varchar(200) NULL, "empresa" varchar(10) NOT NULL, "centro_padre_id" bigint NULL);
--
-- Create model CuentaContable
--
CREATE TABLE "cont_cuenta_contable" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "codigo" varchar(20) NOT NULL, "nombre" varchar(200) NOT NULL, "nivel" integer NOT NULL, "tipo" varchar(10) NOT NULL, "naturaleza" varchar(10) NOT NULL, "descripcion" text NULL, "acepta_movimiento" boolean NOT NULL, "requiere_centro_costo" boolean NOT NULL, "requiere_tercero" boolean NOT NULL, "empresa" varchar(10) NOT NULL, "cuenta_padre_id" bigint NULL);
--
-- Create model EjercicioFiscal
--
CREATE TABLE "cont_ejercicio_fiscal" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "anio" integer NOT NULL UNIQUE, "descripcion" varchar(100) NOT NULL, "fecha_inicio" date NOT NULL, "fecha_fin" date NOT NULL, "estado" varchar(20) NOT NULL, "empresa" varchar(10) NOT NULL);
--
-- Create model GrupoCuenta
--
CREATE TABLE "cont_grupo_cuenta" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "codigo" varchar(1) NOT NULL UNIQUE, "nombre" varchar(100) NOT NULL, "naturaleza" varchar(10) NOT NULL, "descripcion" text NULL, "orden" integer NOT NULL);
--
-- Create model Moneda
--
CREATE TABLE "cont_moneda" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "codigo" varchar(3) NOT NULL UNIQUE, "nombre" varchar(100) NOT NULL, "simbolo" varchar(5) NOT NULL, "es_local" boolean NOT NULL, "decimales" integer NOT NULL);
--
-- Create model PoliticaContable
--
CREATE TABLE "cont_politica_contable" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "titulo" varchar(200) NOT NULL, "descripcion" text NOT NULL, "tipo_cambio" varchar(20) NULL, "fecha_vigencia" date NOT NULL, "nic_relacionada" varchar(50) NULL, "empresa" varchar(10) NOT NULL);
--
-- Create model TipoAsiento
--
CREATE TABLE "cont_tipo_asiento" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "codigo" varchar(10) NOT NULL UNIQUE, "nombre" varchar(100) NOT NULL, "prefijo" varchar(5) NOT NULL, "descripcion" text NULL, "es_automatico" boolean NOT NULL);
--
-- Create model Provision
--
CREATE TABLE "cont_provision" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "descripcion" varchar(500) NOT NULL, "tipo" varchar(30) NOT NULL, "monto_estimado" numeric(18, 2) NOT NULL, "probabilidad" varchar(20) NOT NULL, "fecha_origen" date NOT NULL, "fecha_vencimiento" date NULL, "notas" text NULL, "empresa" varchar(10) NOT NULL, "cuenta_id" bigint NOT NULL);
--
-- Create model PeriodoContable
--
CREATE TABLE "cont_periodo_contable" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "numero" integer NOT NULL, "nombre" varchar(50) NOT NULL, "fecha_inicio" date NOT NULL, "fecha_fin" date NOT NULL, "estado" varchar(20) NOT NULL, "ejercicio_id" bigint NOT NULL);
--
-- Create model InstrumentoFinanciero
--
CREATE TABLE "cont_instrumento_financiero" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "codigo" varchar(20) NOT NULL, "descripcion" varchar(500) NOT NULL, "tipo" varchar(20) NOT NULL, "clasificacion" varchar(30) NOT NULL, "valor_nominal" numeric(18, 2) NOT NULL, "valor_razonable" numeric(18, 2) NOT NULL, "tasa_interes" numeric(8, 4) NOT NULL, "fecha_emision" date NOT NULL, "fecha_vencimiento" date NULL, "empresa" varchar(10) NOT NULL, "cuenta_id" bigint NOT NULL);
--
-- Create model ImpuestoDiferido
--
CREATE TABLE "cont_impuesto_diferido" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "descripcion" varchar(500) NOT NULL, "tipo" varchar(10) NOT NULL, "base_contable" numeric(18, 2) NOT NULL, "base_fiscal" numeric(18, 2) NOT NULL, "diferencia_temporaria" numeric(18, 2) NOT NULL, "tasa_impuesto" numeric(5, 2) NOT NULL, "impuesto_diferido" numeric(18, 2) NOT NULL, "empresa" varchar(10) NOT NULL, "cuenta_id" bigint NOT NULL, "periodo_id" bigint NOT NULL);
--
-- Create model HechoPosterior
--
CREATE TABLE "cont_hecho_posterior" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "tipo" varchar(20) NOT NULL, "descripcion" text NOT NULL, "fecha_hecho" date NOT NULL, "impacto_financiero" numeric(18, 2) NOT NULL, "empresa" varchar(10) NOT NULL, "asiento_ajuste_id" bigint NULL, "ejercicio_id" bigint NOT NULL);
--
-- Create model FlujoEfectivo
--
CREATE TABLE "cont_flujo_efectivo" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "categoria" varchar(20) NOT NULL, "concepto" varchar(500) NOT NULL, "entrada" numeric(18, 2) NOT NULL, "salida" numeric(18, 2) NOT NULL, "neto" numeric(18, 2) NOT NULL, "empresa" varchar(10) NOT NULL, "cuenta_id" bigint NULL, "periodo_id" bigint NOT NULL);
--
-- Create model DeterioroActivo
--
CREATE TABLE "cont_deterioro_activo" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "tipo_activo" varchar(20) NOT NULL, "valor_en_libros" numeric(18, 2) NOT NULL, "importe_recuperable" numeric(18, 2) NOT NULL, "perdida_deterioro" numeric(18, 2) NOT NULL, "fecha_evaluacion" date NOT NULL, "empresa" varchar(10) NOT NULL, "activo_fijo_id" bigint NULL, "activo_intangible_id" bigint NULL, "asiento_id" bigint NULL, "cuenta_perdida_id" bigint NOT NULL);
--
-- Add field grupo to cuentacontable
--
ALTER TABLE "cont_cuenta_contable" ADD COLUMN "grupo_id" bigint NOT NULL CONSTRAINT "cont_cuenta_contable_grupo_id_a0d60404_fk_cont_grupo_cuenta_id" REFERENCES "cont_grupo_cuenta"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "cont_cuenta_contable_grupo_id_a0d60404_fk_cont_grupo_cuenta_id" IMMEDIATE;
--
-- Create model CostoPrestamo
--
CREATE TABLE "cont_costo_prestamo" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "descripcion" varchar(500) NOT NULL, "monto_principal" numeric(18, 2) NOT NULL, "tasa_interes_anual" numeric(8, 4) NOT NULL, "fecha_desembolso" date NOT NULL, "fecha_vencimiento" date NOT NULL, "interes_acumulado" numeric(18, 2) NOT NULL, "capitalizable" boolean NOT NULL, "empresa" varchar(10) NOT NULL, "activo_calificado_id" bigint NULL, "cuenta_interes_id" bigint NOT NULL, "cuenta_prestamo_id" bigint NOT NULL);
--
-- Create model BeneficioEmpleado
--
CREATE TABLE "cont_beneficio_empleado" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "descripcion" varchar(500) NOT NULL, "tipo" varchar(20) NOT NULL, "monto_mensual" numeric(18, 2) NOT NULL, "provision_acumulada" numeric(18, 2) NOT NULL, "numero_empleados" integer NOT NULL, "empresa" varchar(10) NOT NULL, "cuenta_gasto_id" bigint NOT NULL, "cuenta_provision_id" bigint NOT NULL);
--
-- Add field moneda to asientocontable
--
ALTER TABLE "cont_asiento_contable" ADD COLUMN "moneda_id" bigint NULL CONSTRAINT "cont_asiento_contable_moneda_id_205e4b03_fk_cont_moneda_id" REFERENCES "cont_moneda"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "cont_asiento_contable_moneda_id_205e4b03_fk_cont_moneda_id" IMMEDIATE;
--
-- Add field periodo to asientocontable
--
ALTER TABLE "cont_asiento_contable" ADD COLUMN "periodo_id" bigint NOT NULL CONSTRAINT "cont_asiento_contabl_periodo_id_ee8e6271_fk_cont_peri" REFERENCES "cont_periodo_contable"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "cont_asiento_contabl_periodo_id_ee8e6271_fk_cont_peri" IMMEDIATE;
--
-- Add field tipo to asientocontable
--
ALTER TABLE "cont_asiento_contable" ADD COLUMN "tipo_id" bigint NOT NULL CONSTRAINT "cont_asiento_contable_tipo_id_3ef4ebfa_fk_cont_tipo_asiento_id" REFERENCES "cont_tipo_asiento"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "cont_asiento_contable_tipo_id_3ef4ebfa_fk_cont_tipo_asiento_id" IMMEDIATE;
--
-- Add field cuenta to activointangible
--
ALTER TABLE "cont_activo_intangible" ADD COLUMN "cuenta_id" bigint NOT NULL CONSTRAINT "cont_activo_intangib_cuenta_id_a757a04c_fk_cont_cuen" REFERENCES "cont_cuenta_contable"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "cont_activo_intangib_cuenta_id_a757a04c_fk_cont_cuen" IMMEDIATE;
--
-- Add field cuenta_amortizacion to activointangible
--
ALTER TABLE "cont_activo_intangible" ADD COLUMN "cuenta_amortizacion_id" bigint NOT NULL CONSTRAINT "cont_activo_intangib_cuenta_amortizacion__07cbd743_fk_cont_cuen" REFERENCES "cont_cuenta_contable"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "cont_activo_intangib_cuenta_amortizacion__07cbd743_fk_cont_cuen" IMMEDIATE;
--
-- Add field cuenta_activo to activofijo
--
ALTER TABLE "cont_activo_fijo" ADD COLUMN "cuenta_activo_id" bigint NOT NULL CONSTRAINT "cont_activo_fijo_cuenta_activo_id_596402e8_fk_cont_cuen" REFERENCES "cont_cuenta_contable"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "cont_activo_fijo_cuenta_activo_id_596402e8_fk_cont_cuen" IMMEDIATE;
--
-- Add field cuenta_depreciacion to activofijo
--
ALTER TABLE "cont_activo_fijo" ADD COLUMN "cuenta_depreciacion_id" bigint NOT NULL CONSTRAINT "cont_activo_fijo_cuenta_depreciacion__d5021698_fk_cont_cuen" REFERENCES "cont_cuenta_contable"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "cont_activo_fijo_cuenta_depreciacion__d5021698_fk_cont_cuen" IMMEDIATE;
--
-- Add field cuenta_gasto_depreciacion to activofijo
--
ALTER TABLE "cont_activo_fijo" ADD COLUMN "cuenta_gasto_depreciacion_id" bigint NOT NULL CONSTRAINT "cont_activo_fijo_cuenta_gasto_depreci_48da5049_fk_cont_cuen" REFERENCES "cont_cuenta_contable"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "cont_activo_fijo_cuenta_gasto_depreci_48da5049_fk_cont_cuen" IMMEDIATE;
--
-- Create model TipoCambio
--
CREATE TABLE "cont_tipo_cambio" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "fecha" date NOT NULL, "tasa_compra" numeric(18, 6) NOT NULL, "tasa_venta" numeric(18, 6) NOT NULL, "tasa_promedio" numeric(18, 6) NOT NULL, "moneda_id" bigint NOT NULL);
--
-- Create model PropiedadInversion
--
CREATE TABLE "cont_propiedad_inversion" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "codigo" varchar(20) NOT NULL, "descripcion" varchar(500) NOT NULL, "direccion" text NULL, "costo_adquisicion" numeric(18, 2) NOT NULL, "valor_razonable" numeric(18, 2) NOT NULL, "modelo_medicion" varchar(20) NOT NULL, "ingreso_renta_mensual" numeric(18, 2) NOT NULL, "fecha_adquisicion" date NOT NULL, "empresa" varchar(10) NOT NULL, "cuenta_id" bigint NOT NULL);
--
-- Create model LibroMayor
--
CREATE TABLE "cont_libro_mayor" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "saldo_anterior" numeric(18, 2) NOT NULL, "debitos" numeric(18, 2) NOT NULL, "creditos" numeric(18, 2) NOT NULL, "saldo_final" numeric(18, 2) NOT NULL, "empresa" varchar(10) NOT NULL, "cuenta_id" bigint NOT NULL, "periodo_id" bigint NOT NULL);
--
-- Create model Inventario
--
CREATE TABLE "cont_inventario" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "codigo" varchar(20) NOT NULL, "descripcion" varchar(500) NOT NULL, "unidad_medida" varchar(20) NOT NULL, "cantidad" numeric(18, 4) NOT NULL, "costo_unitario" numeric(18, 4) NOT NULL, "costo_total" numeric(18, 2) NOT NULL, "valor_neto_realizable" numeric(18, 2) NOT NULL, "metodo_valoracion" varchar(20) NOT NULL, "stock_minimo" numeric(18, 4) NOT NULL, "empresa" varchar(10) NOT NULL, "cuenta_costo_venta_id" bigint NOT NULL, "cuenta_inventario_id" bigint NOT NULL);
--
-- Create model DetalleAsiento
--
CREATE TABLE "cont_detalle_asiento" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "linea" integer NOT NULL, "concepto" varchar(500) NULL, "debe" numeric(18, 2) NOT NULL, "haber" numeric(18, 2) NOT NULL, "tercero" varchar(200) NULL, "referencia" varchar(100) NULL, "asiento_id" bigint NOT NULL, "centro_costo_id" bigint NULL, "cuenta_id" bigint NOT NULL);
--
-- Create model Depreciacion
--
CREATE TABLE "cont_depreciacion" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "monto" numeric(18, 2) NOT NULL, "depreciacion_acumulada" numeric(18, 2) NOT NULL, "valor_en_libros" numeric(18, 2) NOT NULL, "activo_id" bigint NOT NULL, "asiento_id" bigint NULL, "periodo_id" bigint NOT NULL);
--
-- Alter unique_together for cuentacontable (1 constraint(s))
--
ALTER TABLE "cont_cuenta_contable" ADD CONSTRAINT "cont_cuenta_contable_codigo_empresa_b429d5ac_uniq" UNIQUE ("codigo", "empresa");
--
-- Alter unique_together for asientocontable (1 constraint(s))
--
ALTER TABLE "cont_asiento_contable" ADD CONSTRAINT "cont_asiento_contable_numero_empresa_3ccd419d_uniq" UNIQUE ("numero", "empresa");
--
-- Alter unique_together for activointangible (1 constraint(s))
--
ALTER TABLE "cont_activo_intangible" ADD CONSTRAINT "cont_activo_intangible_codigo_empresa_604dbc15_uniq" UNIQUE ("codigo", "empresa");
--
-- Alter unique_together for activofijo (1 constraint(s))
--
ALTER TABLE "cont_activo_fijo" ADD CONSTRAINT "cont_activo_fijo_codigo_empresa_804f2fe7_uniq" UNIQUE ("codigo", "empresa");
--
-- Create model ActivoBiologico
--
CREATE TABLE "cont_activo_biologico" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "codigo" varchar(20) NOT NULL, "descripcion" varchar(500) NOT NULL, "tipo" varchar(20) NOT NULL, "cantidad" numeric(18, 4) NOT NULL, "unidad_medida" varchar(20) NOT NULL, "valor_razonable" numeric(18, 2) NOT NULL, "costos_venta" numeric(18, 2) NOT NULL, "fecha_medicion" date NOT NULL, "empresa" varchar(10) NOT NULL, "cuenta_id" bigint NOT NULL);
ALTER TABLE "cont_centro_costo" ADD CONSTRAINT "cont_centro_costo_codigo_empresa_82f9a592_uniq" UNIQUE ("codigo", "empresa");
ALTER TABLE "cont_centro_costo" ADD CONSTRAINT "cont_centro_costo_centro_padre_id_4defa304_fk_cont_cent" FOREIGN KEY ("centro_padre_id") REFERENCES "cont_centro_costo" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_centro_costo_centro_padre_id_4defa304" ON "cont_centro_costo" ("centro_padre_id");
ALTER TABLE "cont_cuenta_contable" ADD CONSTRAINT "cont_cuenta_contable_cuenta_padre_id_9f6f476c_fk_cont_cuen" FOREIGN KEY ("cuenta_padre_id") REFERENCES "cont_cuenta_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_cuenta_contable_cuenta_padre_id_9f6f476c" ON "cont_cuenta_contable" ("cuenta_padre_id");
CREATE INDEX "cont_grupo_cuenta_codigo_fe4bb3bb_like" ON "cont_grupo_cuenta" ("codigo" varchar_pattern_ops);
CREATE INDEX "cont_moneda_codigo_2617e5fe_like" ON "cont_moneda" ("codigo" varchar_pattern_ops);
CREATE INDEX "cont_tipo_asiento_codigo_c8b7f7b0_like" ON "cont_tipo_asiento" ("codigo" varchar_pattern_ops);
ALTER TABLE "cont_provision" ADD CONSTRAINT "cont_provision_cuenta_id_edb95835_fk_cont_cuenta_contable_id" FOREIGN KEY ("cuenta_id") REFERENCES "cont_cuenta_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_provision_cuenta_id_edb95835" ON "cont_provision" ("cuenta_id");
ALTER TABLE "cont_periodo_contable" ADD CONSTRAINT "cont_periodo_contable_ejercicio_id_numero_50ee83e2_uniq" UNIQUE ("ejercicio_id", "numero");
ALTER TABLE "cont_periodo_contable" ADD CONSTRAINT "cont_periodo_contabl_ejercicio_id_814a4f42_fk_cont_ejer" FOREIGN KEY ("ejercicio_id") REFERENCES "cont_ejercicio_fiscal" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_periodo_contable_ejercicio_id_814a4f42" ON "cont_periodo_contable" ("ejercicio_id");
ALTER TABLE "cont_instrumento_financiero" ADD CONSTRAINT "cont_instrumento_fin_cuenta_id_4c8a3089_fk_cont_cuen" FOREIGN KEY ("cuenta_id") REFERENCES "cont_cuenta_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_instrumento_financiero_cuenta_id_4c8a3089" ON "cont_instrumento_financiero" ("cuenta_id");
ALTER TABLE "cont_impuesto_diferido" ADD CONSTRAINT "cont_impuesto_diferi_cuenta_id_bca37381_fk_cont_cuen" FOREIGN KEY ("cuenta_id") REFERENCES "cont_cuenta_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cont_impuesto_diferido" ADD CONSTRAINT "cont_impuesto_diferi_periodo_id_c155125b_fk_cont_peri" FOREIGN KEY ("periodo_id") REFERENCES "cont_periodo_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_impuesto_diferido_cuenta_id_bca37381" ON "cont_impuesto_diferido" ("cuenta_id");
CREATE INDEX "cont_impuesto_diferido_periodo_id_c155125b" ON "cont_impuesto_diferido" ("periodo_id");
ALTER TABLE "cont_hecho_posterior" ADD CONSTRAINT "cont_hecho_posterior_asiento_ajuste_id_6333b3a2_fk_cont_asie" FOREIGN KEY ("asiento_ajuste_id") REFERENCES "cont_asiento_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cont_hecho_posterior" ADD CONSTRAINT "cont_hecho_posterior_ejercicio_id_21abbd8b_fk_cont_ejer" FOREIGN KEY ("ejercicio_id") REFERENCES "cont_ejercicio_fiscal" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_hecho_posterior_asiento_ajuste_id_6333b3a2" ON "cont_hecho_posterior" ("asiento_ajuste_id");
CREATE INDEX "cont_hecho_posterior_ejercicio_id_21abbd8b" ON "cont_hecho_posterior" ("ejercicio_id");
ALTER TABLE "cont_flujo_efectivo" ADD CONSTRAINT "cont_flujo_efectivo_cuenta_id_a3e3a2cb_fk_cont_cuen" FOREIGN KEY ("cuenta_id") REFERENCES "cont_cuenta_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cont_flujo_efectivo" ADD CONSTRAINT "cont_flujo_efectivo_periodo_id_1efa70f7_fk_cont_peri" FOREIGN KEY ("periodo_id") REFERENCES "cont_periodo_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_flujo_efectivo_cuenta_id_a3e3a2cb" ON "cont_flujo_efectivo" ("cuenta_id");
CREATE INDEX "cont_flujo_efectivo_periodo_id_1efa70f7" ON "cont_flujo_efectivo" ("periodo_id");
ALTER TABLE "cont_deterioro_activo" ADD CONSTRAINT "cont_deterioro_activ_activo_fijo_id_fcae254c_fk_cont_acti" FOREIGN KEY ("activo_fijo_id") REFERENCES "cont_activo_fijo" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cont_deterioro_activo" ADD CONSTRAINT "cont_deterioro_activ_activo_intangible_id_c0f21dfb_fk_cont_acti" FOREIGN KEY ("activo_intangible_id") REFERENCES "cont_activo_intangible" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cont_deterioro_activo" ADD CONSTRAINT "cont_deterioro_activ_asiento_id_9edeb127_fk_cont_asie" FOREIGN KEY ("asiento_id") REFERENCES "cont_asiento_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cont_deterioro_activo" ADD CONSTRAINT "cont_deterioro_activ_cuenta_perdida_id_3c81003e_fk_cont_cuen" FOREIGN KEY ("cuenta_perdida_id") REFERENCES "cont_cuenta_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_deterioro_activo_activo_fijo_id_fcae254c" ON "cont_deterioro_activo" ("activo_fijo_id");
CREATE INDEX "cont_deterioro_activo_activo_intangible_id_c0f21dfb" ON "cont_deterioro_activo" ("activo_intangible_id");
CREATE INDEX "cont_deterioro_activo_asiento_id_9edeb127" ON "cont_deterioro_activo" ("asiento_id");
CREATE INDEX "cont_deterioro_activo_cuenta_perdida_id_3c81003e" ON "cont_deterioro_activo" ("cuenta_perdida_id");
CREATE INDEX "cont_cuenta_contable_grupo_id_a0d60404" ON "cont_cuenta_contable" ("grupo_id");
ALTER TABLE "cont_costo_prestamo" ADD CONSTRAINT "cont_costo_prestamo_activo_calificado_id_667f0200_fk_cont_acti" FOREIGN KEY ("activo_calificado_id") REFERENCES "cont_activo_fijo" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cont_costo_prestamo" ADD CONSTRAINT "cont_costo_prestamo_cuenta_interes_id_844468d0_fk_cont_cuen" FOREIGN KEY ("cuenta_interes_id") REFERENCES "cont_cuenta_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cont_costo_prestamo" ADD CONSTRAINT "cont_costo_prestamo_cuenta_prestamo_id_7200491b_fk_cont_cuen" FOREIGN KEY ("cuenta_prestamo_id") REFERENCES "cont_cuenta_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_costo_prestamo_activo_calificado_id_667f0200" ON "cont_costo_prestamo" ("activo_calificado_id");
CREATE INDEX "cont_costo_prestamo_cuenta_interes_id_844468d0" ON "cont_costo_prestamo" ("cuenta_interes_id");
CREATE INDEX "cont_costo_prestamo_cuenta_prestamo_id_7200491b" ON "cont_costo_prestamo" ("cuenta_prestamo_id");
ALTER TABLE "cont_beneficio_empleado" ADD CONSTRAINT "cont_beneficio_emple_cuenta_gasto_id_4485dfe3_fk_cont_cuen" FOREIGN KEY ("cuenta_gasto_id") REFERENCES "cont_cuenta_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cont_beneficio_empleado" ADD CONSTRAINT "cont_beneficio_emple_cuenta_provision_id_6139798c_fk_cont_cuen" FOREIGN KEY ("cuenta_provision_id") REFERENCES "cont_cuenta_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_beneficio_empleado_cuenta_gasto_id_4485dfe3" ON "cont_beneficio_empleado" ("cuenta_gasto_id");
CREATE INDEX "cont_beneficio_empleado_cuenta_provision_id_6139798c" ON "cont_beneficio_empleado" ("cuenta_provision_id");
CREATE INDEX "cont_asiento_contable_moneda_id_205e4b03" ON "cont_asiento_contable" ("moneda_id");
CREATE INDEX "cont_asiento_contable_periodo_id_ee8e6271" ON "cont_asiento_contable" ("periodo_id");
CREATE INDEX "cont_asiento_contable_tipo_id_3ef4ebfa" ON "cont_asiento_contable" ("tipo_id");
CREATE INDEX "cont_activo_intangible_cuenta_id_a757a04c" ON "cont_activo_intangible" ("cuenta_id");
CREATE INDEX "cont_activo_intangible_cuenta_amortizacion_id_07cbd743" ON "cont_activo_intangible" ("cuenta_amortizacion_id");
CREATE INDEX "cont_activo_fijo_cuenta_activo_id_596402e8" ON "cont_activo_fijo" ("cuenta_activo_id");
CREATE INDEX "cont_activo_fijo_cuenta_depreciacion_id_d5021698" ON "cont_activo_fijo" ("cuenta_depreciacion_id");
CREATE INDEX "cont_activo_fijo_cuenta_gasto_depreciacion_id_48da5049" ON "cont_activo_fijo" ("cuenta_gasto_depreciacion_id");
ALTER TABLE "cont_tipo_cambio" ADD CONSTRAINT "cont_tipo_cambio_moneda_id_fecha_7f8f2a34_uniq" UNIQUE ("moneda_id", "fecha");
ALTER TABLE "cont_tipo_cambio" ADD CONSTRAINT "cont_tipo_cambio_moneda_id_c1402ec7_fk_cont_moneda_id" FOREIGN KEY ("moneda_id") REFERENCES "cont_moneda" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_tipo_cambio_moneda_id_c1402ec7" ON "cont_tipo_cambio" ("moneda_id");
ALTER TABLE "cont_propiedad_inversion" ADD CONSTRAINT "cont_propiedad_inversion_codigo_empresa_d576e72a_uniq" UNIQUE ("codigo", "empresa");
ALTER TABLE "cont_propiedad_inversion" ADD CONSTRAINT "cont_propiedad_inver_cuenta_id_7e1902dd_fk_cont_cuen" FOREIGN KEY ("cuenta_id") REFERENCES "cont_cuenta_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_propiedad_inversion_cuenta_id_7e1902dd" ON "cont_propiedad_inversion" ("cuenta_id");
ALTER TABLE "cont_libro_mayor" ADD CONSTRAINT "cont_libro_mayor_cuenta_id_periodo_id_empresa_5c8964de_uniq" UNIQUE ("cuenta_id", "periodo_id", "empresa");
ALTER TABLE "cont_libro_mayor" ADD CONSTRAINT "cont_libro_mayor_cuenta_id_c72ad3ba_fk_cont_cuenta_contable_id" FOREIGN KEY ("cuenta_id") REFERENCES "cont_cuenta_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cont_libro_mayor" ADD CONSTRAINT "cont_libro_mayor_periodo_id_1caa71cf_fk_cont_peri" FOREIGN KEY ("periodo_id") REFERENCES "cont_periodo_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_libro_mayor_cuenta_id_c72ad3ba" ON "cont_libro_mayor" ("cuenta_id");
CREATE INDEX "cont_libro_mayor_periodo_id_1caa71cf" ON "cont_libro_mayor" ("periodo_id");
ALTER TABLE "cont_inventario" ADD CONSTRAINT "cont_inventario_codigo_empresa_f8e27e65_uniq" UNIQUE ("codigo", "empresa");
ALTER TABLE "cont_inventario" ADD CONSTRAINT "cont_inventario_cuenta_costo_venta_i_3e01e918_fk_cont_cuen" FOREIGN KEY ("cuenta_costo_venta_id") REFERENCES "cont_cuenta_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cont_inventario" ADD CONSTRAINT "cont_inventario_cuenta_inventario_id_dbb5b365_fk_cont_cuen" FOREIGN KEY ("cuenta_inventario_id") REFERENCES "cont_cuenta_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_inventario_cuenta_costo_venta_id_3e01e918" ON "cont_inventario" ("cuenta_costo_venta_id");
CREATE INDEX "cont_inventario_cuenta_inventario_id_dbb5b365" ON "cont_inventario" ("cuenta_inventario_id");
ALTER TABLE "cont_detalle_asiento" ADD CONSTRAINT "cont_detalle_asiento_asiento_id_linea_6ac7e236_uniq" UNIQUE ("asiento_id", "linea");
ALTER TABLE "cont_detalle_asiento" ADD CONSTRAINT "cont_detalle_asiento_asiento_id_33d8c5e5_fk_cont_asie" FOREIGN KEY ("asiento_id") REFERENCES "cont_asiento_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cont_detalle_asiento" ADD CONSTRAINT "cont_detalle_asiento_centro_costo_id_b0e2fc7e_fk_cont_cent" FOREIGN KEY ("centro_costo_id") REFERENCES "cont_centro_costo" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cont_detalle_asiento" ADD CONSTRAINT "cont_detalle_asiento_cuenta_id_ec811637_fk_cont_cuen" FOREIGN KEY ("cuenta_id") REFERENCES "cont_cuenta_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_detalle_asiento_asiento_id_33d8c5e5" ON "cont_detalle_asiento" ("asiento_id");
CREATE INDEX "cont_detalle_asiento_centro_costo_id_b0e2fc7e" ON "cont_detalle_asiento" ("centro_costo_id");
CREATE INDEX "cont_detalle_asiento_cuenta_id_ec811637" ON "cont_detalle_asiento" ("cuenta_id");
ALTER TABLE "cont_depreciacion" ADD CONSTRAINT "cont_depreciacion_activo_id_periodo_id_59568398_uniq" UNIQUE ("activo_id", "periodo_id");
ALTER TABLE "cont_depreciacion" ADD CONSTRAINT "cont_depreciacion_activo_id_b630230b_fk_cont_activo_fijo_id" FOREIGN KEY ("activo_id") REFERENCES "cont_activo_fijo" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cont_depreciacion" ADD CONSTRAINT "cont_depreciacion_asiento_id_ae6233ab_fk_cont_asie" FOREIGN KEY ("asiento_id") REFERENCES "cont_asiento_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cont_depreciacion" ADD CONSTRAINT "cont_depreciacion_periodo_id_296ba816_fk_cont_peri" FOREIGN KEY ("periodo_id") REFERENCES "cont_periodo_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_depreciacion_activo_id_b630230b" ON "cont_depreciacion" ("activo_id");
CREATE INDEX "cont_depreciacion_asiento_id_ae6233ab" ON "cont_depreciacion" ("asiento_id");
CREATE INDEX "cont_depreciacion_periodo_id_296ba816" ON "cont_depreciacion" ("periodo_id");
ALTER TABLE "cont_activo_biologico" ADD CONSTRAINT "cont_activo_biologico_codigo_empresa_51e777b8_uniq" UNIQUE ("codigo", "empresa");
ALTER TABLE "cont_activo_biologico" ADD CONSTRAINT "cont_activo_biologic_cuenta_id_04d9af50_fk_cont_cuen" FOREIGN KEY ("cuenta_id") REFERENCES "cont_cuenta_contable" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cont_activo_biologico_cuenta_id_04d9af50" ON "cont_activo_biologico" ("cuenta_id");
COMMIT;

-- MIGRATION 0002
BEGIN;
--
-- Add field tipo_inventario to inventario
--
ALTER TABLE "cont_inventario" ADD COLUMN "tipo_inventario" varchar(30) DEFAULT 'OTROS' NOT NULL;
ALTER TABLE "cont_inventario" ALTER COLUMN "tipo_inventario" DROP DEFAULT;
--
-- Add field nomenclatura to inventario
--
ALTER TABLE "cont_inventario" ADD COLUMN "nomenclatura" varchar(120) DEFAULT '' NOT NULL;
ALTER TABLE "cont_inventario" ALTER COLUMN "nomenclatura" DROP DEFAULT;
COMMIT;

-- MIGRATION 0003
BEGIN;
--
-- Create model TipoInventario
--
CREATE TABLE "cont_tipo_inventario" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "is_active" boolean NOT NULL, "created_by" varchar(100) NULL, "updated_by" varchar(100) NULL, "empresa" varchar(10) NOT NULL, "nombre" varchar(120) NOT NULL, "orden" smallint NOT NULL CHECK ("orden" >= 0), "notas" text NOT NULL, "codigo_legacy" varchar(30) NOT NULL);
--
-- Add field tipo_catalogo to inventario
--
ALTER TABLE "cont_inventario" ADD COLUMN "tipo_catalogo_id" bigint NULL CONSTRAINT "cont_inventario_tipo_catalogo_id_29f2eae0_fk_cont_tipo" REFERENCES "cont_tipo_inventario"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "cont_inventario_tipo_catalogo_id_29f2eae0_fk_cont_tipo" IMMEDIATE;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Remove field tipo_inventario from inventario
--
ALTER TABLE "cont_inventario" DROP COLUMN "tipo_inventario" CASCADE;
--
-- Rename field tipo_catalogo on inventario to tipo_inventario
--
ALTER TABLE "cont_inventario" RENAME COLUMN "tipo_catalogo_id" TO "tipo_inventario_id";
ALTER TABLE "cont_tipo_inventario" ADD CONSTRAINT "cont_tipo_inventario_empresa_nombre_7311eda1_uniq" UNIQUE ("empresa", "nombre");
CREATE INDEX "cont_tipo_inventario_empresa_a1d3d523" ON "cont_tipo_inventario" ("empresa");
CREATE INDEX "cont_tipo_inventario_empresa_a1d3d523_like" ON "cont_tipo_inventario" ("empresa" varchar_pattern_ops);
CREATE INDEX "cont_inventario_tipo_inventario_id_80a96e36" ON "cont_inventario" ("tipo_inventario_id");
COMMIT;
