# Generated by Django 4.2.27 on 2026-04-05 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_superusuario',
            field=models.BooleanField(default=False, help_text='Si está activo, puede acceder a todos los módulos sin contraseña por módulo.', verbose_name='Superusuario'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='usuarios/fotos/', verbose_name='Foto de Perfil'),
        ),
        migrations.CreateModel(
            name='UsuarioAccesoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo_modulo', models.CharField(db_collation='latin1_swedish_ci', max_length=32, verbose_name='Código de módulo')),
                ('password', models.CharField(db_collation='latin1_swedish_ci', max_length=255, verbose_name='Contraseña del módulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_modulo', to='usuarios.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Acceso a módulo',
                'verbose_name_plural': 'Accesos por módulo',
                'db_table': 'mod_usuarios_acceso_modulo',
                'indexes': [models.Index(fields=['codigo_modulo'], name='mod_usuario_codigo__7b234e_idx')],
                'unique_together': {('usuario', 'codigo_modulo')},
            },
        ),
    ]
