# Generated by Django 4.2.27 on 2026-04-05 17:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('presupuestos', '0007_operacionmanual_delete_gastomanual'),
        ('administrativo_main', '0006_alter_proveedor_documentacion'),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitacionCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_invitacion', models.DateField(blank=True, null=True, verbose_name='Fecha de invitación')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de respuesta'), ('RECIBIDA', 'Oferta recibida'), ('DECLINADA', 'Declinada')], default='PENDIENTE', max_length=15)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitaciones_cotizacion', to='administrativo_main.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Invitación a cotizar',
                'verbose_name_plural': 'Invitaciones a cotizar',
                'db_table': 'compras_invitacion_cotizacion',
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.CharField(db_index=True, max_length=10, verbose_name='Empresa/Municipio')),
                ('numero', models.CharField(max_length=30, verbose_name='Número OC')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('APROBADA', 'Aprobada'), ('PARCIAL', 'Recibido parcial'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=15)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto total')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('compromiso', models.ForeignKey(blank=True, help_text='Reserva de fondo asociada (cuando exista).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='presupuestos.compromiso', verbose_name='Compromiso presupuestario')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='contabilidad.ejerciciofiscal', verbose_name='Ejercicio fiscal')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='administrativo_main.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'verbose_name_plural': 'Órdenes de compra',
                'db_table': 'compras_orden_compra',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.CharField(db_index=True, max_length=10, verbose_name='Empresa/Municipio')),
                ('numero', models.CharField(max_length=30, verbose_name='Número')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada a aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=15)),
                ('solicitante', models.CharField(blank=True, default='', max_length=120, verbose_name='Solicitante')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('ejercicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisiciones_compras', to='contabilidad.ejerciciofiscal', verbose_name='Ejercicio fiscal')),
            ],
            options={
                'verbose_name': 'Requisición',
                'verbose_name_plural': 'Requisiciones',
                'db_table': 'compras_requisicion',
                'ordering': ['-fecha', '-id'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.CharField(db_index=True, max_length=10, verbose_name='Empresa/Municipio')),
                ('numero', models.CharField(max_length=30, verbose_name='Número')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('fecha_limite_respuesta', models.DateField(blank=True, null=True, verbose_name='Fecha límite de ofertas')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADA', 'Publicada / enviada a proveedores'), ('CERRADA', 'Cerrada sin adjudicar'), ('ADJUDICADA', 'Adjudicada')], default='BORRADOR', max_length=15)),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones / alcance')),
                ('requisicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_cotizacion', to='compras.requisicion', verbose_name='Requisición origen')),
            ],
            options={
                'verbose_name': 'Solicitud de cotización',
                'verbose_name_plural': 'Solicitudes de cotización',
                'db_table': 'compras_solicitud_cotizacion',
                'ordering': ['-fecha', '-id'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='RequisicionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_linea', models.PositiveSmallIntegerField(default=1, verbose_name='Línea')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Cantidad')),
                ('unidad', models.CharField(default='UND', max_length=20, verbose_name='Unidad de medida')),
                ('cuenta_presupuestaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisiciones_detalle', to='presupuestos.cuentapresupuestaria', verbose_name='Código presupuestario')),
                ('inventario', models.ForeignKey(blank=True, help_text='Opcional: enlaza al catálogo NIC 2.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisiciones_detalle', to='contabilidad.inventario', verbose_name='Ítem de inventario (contabilidad)')),
                ('requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.requisicion', verbose_name='Requisición')),
            ],
            options={
                'verbose_name': 'Detalle de requisición',
                'verbose_name_plural': 'Detalles de requisición',
                'db_table': 'compras_requisicion_detalle',
                'ordering': ['requisicion', 'nro_linea'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_linea', models.PositiveSmallIntegerField(default=1, verbose_name='Línea')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('precio_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cuenta_presupuestaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_detalle', to='presupuestos.cuentapresupuestaria', verbose_name='Partida presupuestaria')),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra_detalle', to='contabilidad.inventario', verbose_name='Ítem inventario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.ordencompra', verbose_name='Orden de compra')),
            ],
            options={
                'verbose_name': 'Detalle orden de compra',
                'verbose_name_plural': 'Detalle órdenes de compra',
                'db_table': 'compras_orden_compra_detalle',
                'ordering': ['orden', 'nro_linea'],
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='requisicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='compras.requisicion', verbose_name='Requisición'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='solicitud_cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='compras.solicitudcotizacion', verbose_name='Solicitud de cotización'),
        ),
        migrations.CreateModel(
            name='OfertaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField(verbose_name='Fecha de recepción')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto total ofertado')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas / condiciones')),
                ('es_seleccionada', models.BooleanField(default=False, verbose_name='Oferta seleccionada')),
                ('invitacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oferta', to='compras.invitacioncotizacion', verbose_name='Invitación')),
            ],
            options={
                'verbose_name': 'Oferta de proveedor',
                'verbose_name_plural': 'Ofertas de proveedores',
                'db_table': 'compras_oferta_proveedor',
            },
        ),
        migrations.CreateModel(
            name='MovimientoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.CharField(db_index=True, max_length=10, verbose_name='Empresa/Municipio')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10, verbose_name='Tipo')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Cantidad')),
                ('costo_unitario', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Costo unitario')),
                ('referencia', models.CharField(blank=True, default='', max_length=120, verbose_name='Referencia / documento')),
                ('notas', models.TextField(blank=True, default='', verbose_name='Notas')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_bodega', to='contabilidad.inventario', verbose_name='Ítem inventario')),
                ('orden_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_bodega', to='compras.ordencompradetalle', verbose_name='Línea OC origen (entrada)')),
            ],
            options={
                'verbose_name': 'Movimiento de bodega',
                'verbose_name_plural': 'Movimientos de bodega',
                'db_table': 'compras_movimiento_bodega',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='invitacioncotizacion',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='compras.solicitudcotizacion', verbose_name='Solicitud'),
        ),
        migrations.AlterUniqueTogether(
            name='ordencompra',
            unique_together={('empresa', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='invitacioncotizacion',
            unique_together={('solicitud', 'proveedor')},
        ),
    ]
