# Generated by Django 4.2.27 on 2026-04-05 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisiciondetalle',
            name='inventario',
            field=models.ForeignKey(blank=True, help_text='Obligatorio en cada línea: catálogo NIC 2; la existencia en bodega es Inventario.cantidad.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requisiciones_detalle', to='contabilidad.inventario', verbose_name='Material / ítem de bodega (inventario)'),
        ),
    ]
