# Generated by Django 4.2.27 on 2026-04-05 17:57

from collections import defaultdict

from django.db import migrations, models


def _backfill_correlativo(apps, schema_editor):
    Requisicion = apps.get_model("compras", "Requisicion")
    rows = list(Requisicion.objects.all().order_by("empresa", "ejercicio_id", "fecha", "id"))
    buckets = defaultdict(int)
    to_update = []
    for r in rows:
        key = (r.empresa, r.ejercicio_id)
        buckets[key] += 1
        r.correlativo = buckets[key]
        to_update.append(r)
    if to_update:
        Requisicion.objects.bulk_update(to_update, ["correlativo"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_requisicion_inventario_bodega_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicion',
            name='correlativo',
            field=models.PositiveIntegerField(default=0, help_text='Secuencial por empresa y ejercicio fiscal (asignación automática).', verbose_name='N° correlativo'),
        ),
        migrations.RunPython(_backfill_correlativo, migrations.RunPython.noop),
    ]
