# Generated by Django 4.2.27 on 2026-04-05 18:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('compras', '0003_requisicion_correlativo_ejercicio_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='texto_marco_oncae',
            field=models.TextField(blank=True, default='', help_text='Texto para impresión de convocatoria (bases, normativa aplicable).', verbose_name='Marco legal / referencia ONCAE'),
        ),
        migrations.CreateModel(
            name='SolicitudCotizacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_linea', models.PositiveSmallIntegerField(default=1, verbose_name='Línea')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Cantidad')),
                ('unidad', models.CharField(default='UND', max_length=20, verbose_name='Unidad')),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_cotizacion_detalle', to='contabilidad.inventario', verbose_name='Material / inventario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.solicitudcotizacion', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Detalle solicitud de cotización',
                'verbose_name_plural': 'Detalles solicitud de cotización',
                'db_table': 'compras_solicitud_cotizacion_detalle',
                'ordering': ['solicitud', 'nro_linea'],
            },
        ),
    ]
