# Generated by Django 5.2.1 on 2025-05-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='usuario',
        ),
    ]
