# Generated by Django 5.2.1 on 2025-07-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0002_rename_username_usuario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=4)),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'actividad',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identidad', models.CharField(max_length=31, unique=True)),
                ('nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Identificación',
                'verbose_name_plural': 'Identificaciones',
                'db_table': 'identificacion',
            },
        ),
        migrations.CreateModel(
            name='PagoVariosTemp',
            fields=[
                ('recibo', models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=16)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('identidad', models.CharField(blank=True, max_length=31, null=True)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('oficina', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('facturadora', models.CharField(blank=True, max_length=45, null=True)),
                ('aplicado', models.CharField(default='0', max_length=1)),
                ('traslado', models.CharField(default='0', max_length=1)),
                ('solvencia', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('fecha_solv', models.DateField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('vl_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deposito', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('cajero', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.CharField(blank=True, max_length=30, null=True)),
                ('referencia', models.CharField(blank=True, max_length=20, null=True)),
                ('banco', models.CharField(blank=True, max_length=3, null=True)),
                ('Tipofa', models.CharField(default=' ', max_length=1)),
                ('Rtm', models.CharField(default=' ', max_length=20)),
                ('expe', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('pagodia', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('rcaja', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('Direccion', models.CharField(default=' ', max_length=80)),
                ('Rfechapag', models.DateField(blank=True, null=True)),
                ('permiso', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('Fechavence', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(default=' ', max_length=100)),
                ('prima', models.CharField(blank=True, default='', max_length=1)),
                ('categoria', models.CharField(blank=True, default='', max_length=2)),
                ('sexo', models.CharField(blank=True, default='', max_length=1)),
                ('rtn', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'pagovariostemp',
            },
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('empre', models.CharField(max_length=4, verbose_name='Empresa')),
                ('rtm', models.CharField(max_length=16, verbose_name='RTM')),
                ('expe', models.CharField(max_length=12, verbose_name='Expediente')),
                ('nombrenego', models.CharField(blank=True, max_length=100, null=True)),
                ('comerciante', models.CharField(blank=True, max_length=100, null=True)),
                ('identidad', models.CharField(default='0', max_length=20)),
                ('rtnpersonal', models.CharField(blank=True, max_length=20, null=True)),
                ('rtnnego', models.CharField(blank=True, max_length=17, null=True)),
                ('catastral', models.CharField(default='0', max_length=15)),
                ('identidadrep', models.CharField(blank=True, max_length=20, null=True)),
                ('representante', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('actividad', models.CharField(blank=True, max_length=12, null=True)),
                ('categoria', models.CharField(blank=True, max_length=12, null=True)),
                ('estatus', models.CharField(blank=True, default='', max_length=1)),
                ('descriestatus', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_ini', models.DateField(blank=True, null=True)),
                ('fecha_can', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('socios', models.CharField(blank=True, default='', max_length=250)),
                ('correo', models.CharField(blank=True, max_length=35, null=True)),
                ('pagweb', models.CharField(blank=True, max_length=40, null=True)),
                ('comentario', models.TextField(blank=True, max_length=15000, null=True)),
                ('descriactividad', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, max_length=10, null=True)),
                ('fechasys', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'db_table': 'negocios',
                'unique_together': {('empre', 'rtm', 'expe')},
            },
        ),
    ]
