# Generated by Django 5.2.1 on 2025-07-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0003_actividad_identificacion_pagovariostemp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoRecibos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('solvencia', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Número de Recibo',
                'verbose_name_plural': 'Números de Recibos',
                'db_table': 'norecibos',
            },
        ),
    ]
