# Generated by Django 5.2.1 on 2025-07-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0004_norecibos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagovariostemp',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
