# Generated by Django 5.2.1 on 2025-07-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0005_alter_pagovariostemp_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagovariostemp',
            options={'ordering': ['-fecha', '-recibo'], 'verbose_name': 'Pago Varios Temporal', 'verbose_name_plural': 'Pagos Varios Temporales'},
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='Fechavence',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='Rfechapag',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago Real'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='Rtm',
            field=models.CharField(default=' ', max_length=20, verbose_name='RTM'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='Tipofa',
            field=models.CharField(default=' ', max_length=1, verbose_name='Tipo de Factura'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='aplicado',
            field=models.CharField(default='0', max_length=1, verbose_name='Aplicado'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='banco',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='cajero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cajero'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='codigo',
            field=models.CharField(max_length=16, verbose_name='Código de Actividad'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='comentario',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='deposito',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1, verbose_name='Depósito'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='direccion',
            field=models.CharField(default=' ', max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='expe',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Expediente'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='facturadora',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Facturadora'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='fecha_solv',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Solvencia'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='identidad',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Identidad'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='oficina',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='pagodia',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Pago del Día'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='permiso',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Permiso'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='prima',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='Prima'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='rcaja',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Recibo de Caja'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='recibo',
            field=models.DecimalField(decimal_places=0, max_digits=12, primary_key=True, serialize=False, verbose_name='Número de Recibo'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='referencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='rtn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RTN'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='sexo',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='solvencia',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Solvencia'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='traslado',
            field=models.CharField(default='0', max_length=1, verbose_name='Traslado'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='usuario',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='vl_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Unitario'),
        ),
    ]
