# Generated by Django 5.2.1 on 2025-07-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0006_alter_pagovariostemp_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagovariostemp',
            name='empresa',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='pagovariostemp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='Direccion',
            field=models.CharField(default=' ', max_length=80, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='recibo',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Número de Recibo'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total'),
        ),
    ]
