# Generated by Django 5.2.1 on 2025-07-19 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0007_pagovariostemp_empresa_pagovariostemp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagovariostemp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
