# Generated by Django 5.2.1 on 2025-07-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0008_alter_pagovariostemp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagovariostemp',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
