# Generated by Django 5.2.1 on 2025-07-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0011_fix_autoincrement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagovariostemp',
            name='oficina',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Oficina'),
        ),
    ]
