# Generated by Django 5.2.1 on 2025-07-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0012_alter_pagovariostemp_oficina_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='cx',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Coordenada X'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='cy',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Coordenada Y'),
        ),
        migrations.AlterUniqueTogether(
            name='actividad',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=4)),
                ('codigo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'oficina',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
    ]
