# Generated by Django 5.2.1 on 2025-07-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0013_negocio_cx_negocio_cy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='catastral',
            field=models.CharField(default='0', max_length=17),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='rtnnego',
            field=models.CharField(blank=True, max_length=19, null=True),
        ),
    ]
