# Generated by Django 5.2.1 on 2025-07-28 02:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0014_alter_negocio_catastral_alter_negocio_rtnnego'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombres', 'apellidos', 'usuario'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to='tributario_app.usuario', verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Intentos Fallidos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='identidad',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Identidad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Usuario Activo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Es Personal'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Es Superusuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado Hasta'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='notas',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='oficina',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Oficina'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Contraseña Cambiada'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rtn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RTN'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre de Usuario'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['usuario'], name='usuarios_usuario_cce775_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='usuarios_email_0ff7b3_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['identidad'], name='usuarios_identid_a33a62_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['is_active'], name='usuarios_is_acti_8ee55c_idx'),
        ),
    ]
