# Generated by Django 5.2.1 on 2025-07-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0015_alter_usuario_options_usuario_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Contraseña'),
        ),
    ]
