# Generated by Django 5.2.1 on 2025-07-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0016_alter_usuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(default='', max_length=4, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=29, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipio',
                'ordering': ['codigo'],
            },
        ),
    ]
