# Generated by Django 5.2.1 on 2025-07-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0017_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.CharField(default='0001', max_length=4, verbose_name='Código de Empresa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=150, verbose_name='Nombre de Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together={('empresa', 'usuario')},
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['empresa'], name='usuarios_empresa_57e993_idx'),
        ),
    ]
