# Generated by Django 5.2.1 on 2025-07-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0018_usuario_empresa_alter_usuario_usuario_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='empresa',
            field=models.CharField(db_collation='latin1_swedish_ci', default='', max_length=4, verbose_name='Código de Empresa'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=255, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=15, verbose_name='Nombre de Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together={('empresa', 'usuario', 'password')},
        ),
    ]
