# Generated by Django 5.2.1 on 2025-07-28 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0019_alter_usuario_unique_together_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombre', 'usuario'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='usuarios_email_0ff7b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='usuario',
            name='usuarios_identid_a33a62_idx',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='identidad',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombres',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='oficina',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='password_changed_at',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rtn',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='updated_at',
        ),
    ]
