# Generated by Django 5.2.1 on 2025-07-28 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0020_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usuario',
            name='usuarios_is_acti_8ee55c_idx',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='locked_until',
        ),
    ]
