# Generated by Django 5.2.1 on 2025-07-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0021_remove_usuario_usuarios_is_acti_8ee55c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='actividad',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=20, null=True, verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='catastral',
            field=models.CharField(db_collation='latin1_swedish_ci', default='0', max_length=17, verbose_name='Catastral'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='categoria',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', max_length=2, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='celular',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=1, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='comentario',
            field=models.TextField(blank=True, db_collation='latin1_swedish_ci', max_length=15000, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='comerciante',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=100, null=True, verbose_name='Comerciante'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='correo',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=35, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='cx',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=12, verbose_name='Coordenada X'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='cy',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=12, null=True, verbose_name='Coordenada Y'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='descriactividad',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=100, null=True, verbose_name='Descripción Actividad'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='descriestatus',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=50, null=True, verbose_name='Descripción Estatus'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='direccion',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='empre',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=4, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='estatus',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', max_length=1, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='expe',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=12, verbose_name='Expediente'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='fecha_can',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Cancelación'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='fecha_ini',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='fechasys',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Sistema'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='identidad',
            field=models.CharField(db_collation='latin1_swedish_ci', default='0', max_length=20, verbose_name='Identidad'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='identidadrep',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=20, null=True, verbose_name='Identidad Representante'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='nombrenego',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=100, null=True, verbose_name='Nombre del Negocio'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='pagweb',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=40, null=True, verbose_name='Página Web'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='representante',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=100, null=True, verbose_name='Representante'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='rtm',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=16, verbose_name='RTM'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='rtnnego',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=19, null=True, verbose_name='RTN Negocio'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='rtnpersonal',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=20, null=True, verbose_name='RTN Personal'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='socios',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', max_length=250, verbose_name='Socios'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='telefono',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=9, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='usuario',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=10, null=True, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['nombrenego'], name='negocios_nombren_3652c3_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['comerciante'], name='negocios_comerci_af75b5_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['identidad'], name='negocios_identid_6484c5_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['rtm'], name='negocios_rtm_f3be6e_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['expe'], name='negocios_expe_d400ca_idx'),
        ),
        migrations.AddIndex(
            model_name='negocio',
            index=models.Index(fields=['actividad'], name='negocios_activid_01b7a0_idx'),
        ),
    ]
