# Generated by Django 5.2.1 on 2025-08-03 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0022_alter_negocio_actividad_alter_negocio_catastral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Concepto')),
                ('tipo', models.CharField(choices=[('IMPUESTO', 'Impuesto'), ('TASA', 'Tasa'), ('SERVICIO', 'Servicio'), ('MULTA', 'Multa'), ('OTRO', 'Otro')], default='TASA', max_length=10, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('valor_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Base')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Porcentaje (%)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
            ],
            options={
                'verbose_name': 'Concepto de Facturación',
                'verbose_name_plural': 'Conceptos de Facturación',
                'db_table': 'conceptos_facturacion',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Período')),
                ('tipo_periodo', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=10, verbose_name='Tipo de Período')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
            ],
            options={
                'verbose_name': 'Período de Facturación',
                'verbose_name_plural': 'Períodos de Facturación',
                'db_table': 'periodos_facturacion',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AlterField(
            model_name='negocio',
            name='actividad',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=20, verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='catastral',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=17, verbose_name='Catastral'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='categoria',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=2, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='celular',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=1, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='comentario',
            field=models.TextField(blank=True, db_collation='latin1_swedish_ci', null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='comerciante',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=100, verbose_name='Comerciante'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='correo',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=35, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='cx',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=11, verbose_name='Coordenada X'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='cy',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=11, verbose_name='Coordenada Y'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='descriactividad',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=100, verbose_name='Descripción Actividad'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='descriestatus',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=50, verbose_name='Descripción Estatus'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='direccion',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='estatus',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=1, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='identidad',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=20, verbose_name='Identidad'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='identidadrep',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=20, verbose_name='Identidad Representante'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='nombrenego',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=100, verbose_name='Nombre del Negocio'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='pagweb',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=40, verbose_name='Página Web'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='representante',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=100, verbose_name='Representante'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='rtnnego',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=19, verbose_name='RTN Negocio'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='rtnpersonal',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=20, verbose_name='RTN Personal'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='socios',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=250, verbose_name='Socios'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='telefono',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=9, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='usuario',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=10, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='ConfiguracionFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=4, verbose_name='Empresa')),
                ('prefijo_factura', models.CharField(default='FAC', max_length=10, verbose_name='Prefijo Factura')),
                ('secuencia_factura', models.IntegerField(default=1, verbose_name='Secuencia Factura')),
                ('dias_vencimiento', models.IntegerField(default=30, verbose_name='Días para Vencimiento')),
                ('aplicar_intereses', models.BooleanField(default=True, verbose_name='Aplicar Intereses')),
                ('porcentaje_interes', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='Porcentaje Interés (%)')),
                ('aplicar_multas', models.BooleanField(default=True, verbose_name='Aplicar Multas')),
                ('monto_multas', models.DecimalField(decimal_places=2, default=50.0, max_digits=12, verbose_name='Monto Multas')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
            ],
            options={
                'verbose_name': 'Configuración de Facturación',
                'verbose_name_plural': 'Configuraciones de Facturación',
                'db_table': 'configuracion_facturacion',
                'unique_together': {('empresa',)},
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True, verbose_name='Número de Factura')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotal')),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('VENCIDA', 'Vencida'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('usuario_creacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario Creación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tributario_app.negocio', verbose_name='Negocio')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tributario_app.periodofacturacion', verbose_name='Período')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Cantidad')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Subtotal')),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Impuestos')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tributario_app.conceptofacturacion', verbose_name='Concepto')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tributario_app.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
                'db_table': 'detalles_factura',
                'ordering': ['factura', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='HistorialFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cambio', models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('PAGO', 'Pago'), ('ANULACION', 'Anulación'), ('ESTADO', 'Cambio de Estado')], max_length=15, verbose_name='Tipo de Cambio')),
                ('descripcion', models.TextField(verbose_name='Descripción del Cambio')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor Nuevo')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuario')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tributario_app.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Historial de Facturación',
                'verbose_name_plural': 'Historial de Facturación',
                'db_table': 'historial_facturacion',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=4, verbose_name='Empresa')),
                ('codigo', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=20, verbose_name='Código')),
                ('descripcion', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=200, null=True, verbose_name='Descripción')),
                ('cuenta', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=1, null=True, verbose_name='Cuenta')),
                ('cuntarez', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=1, null=True, verbose_name='Cuenta Rez')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor')),
                ('categoria', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=1, null=True, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
                'db_table': 'rubros',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['empresa'], name='rubros_empresa_2ba792_idx'), models.Index(fields=['codigo'], name='rubros_codigo_413d1d_idx'), models.Index(fields=['empresa', 'codigo'], name='rubros_empresa_37915f_idx')],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='PagoFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(max_length=20, unique=True, verbose_name='Número de Recibo')),
                ('fecha_pago', models.DateField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Pagado')),
                ('forma_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('DEPOSITO', 'Depósito')], default='EFECTIVO', max_length=15, verbose_name='Forma de Pago')),
                ('referencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Referencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('usuario_pago', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario Pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='tributario_app.factura', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Pago de Factura',
                'verbose_name_plural': 'Pagos de Factura',
                'db_table': 'pagos_factura',
                'ordering': ['-fecha_pago'],
                'indexes': [models.Index(fields=['numero_recibo'], name='pagos_factu_numero__78fb1f_idx'), models.Index(fields=['factura'], name='pagos_factu_factura_587704_idx'), models.Index(fields=['fecha_pago'], name='pagos_factu_fecha_p_9656cd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['numero_factura'], name='facturas_numero__52cd80_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['negocio'], name='facturas_negocio_9ebb92_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['estado'], name='facturas_estado_a2212f_idx'),
        ),
        migrations.AddIndex(
            model_name='factura',
            index=models.Index(fields=['fecha_vencimiento'], name='facturas_fecha_v_1f52e0_idx'),
        ),
    ]
