# Generated by Django 5.2.1 on 2025-08-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0023_conceptofacturacion_periodofacturacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='concepto',
        ),
        migrations.DeleteModel(
            name='ConfiguracionFacturacion',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='negocio',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='historialfacturacion',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='pagofactura',
            name='factura',
        ),
        migrations.RemoveField(
            model_name='rubro',
            name='categoria',
        ),
        migrations.AddField(
            model_name='rubro',
            name='tipo',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=1, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='cuenta',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=20, null=True, verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='cuntarez',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=20, null=True, verbose_name='Cuenta Rezago'),
        ),
        migrations.DeleteModel(
            name='ConceptoFacturacion',
        ),
        migrations.DeleteModel(
            name='DetalleFactura',
        ),
        migrations.DeleteModel(
            name='PeriodoFacturacion',
        ),
        migrations.DeleteModel(
            name='HistorialFacturacion',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='PagoFactura',
        ),
    ]
