# Generated by Django 5.2.1 on 2025-08-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0024_remove_detallefactura_concepto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanArbitrio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=4, verbose_name='Empresa')),
                ('codigo_rubro', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=20, verbose_name='Código de Rubro')),
                ('descripcion_rubro', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=200, null=True, verbose_name='Descripción del Rubro')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('mes', models.IntegerField(verbose_name='Mes')),
                ('valor_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Base')),
                ('factor_correccion', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Factor de Corrección')),
                ('valor_final', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Final')),
                ('estado', models.CharField(db_collation='utf8mb4_0900_ai_ci', default='A', max_length=1, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('usuario', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=30, null=True, verbose_name='Usuario')),
                ('observaciones', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Plan de Arbitrio',
                'verbose_name_plural': 'Planes de Arbitrio',
                'db_table': 'plan_arbitrio',
                'ordering': ['-anio', '-mes', 'codigo_rubro'],
                'indexes': [models.Index(fields=['empresa'], name='plan_arbitr_empresa_d2f2be_idx'), models.Index(fields=['codigo_rubro'], name='plan_arbitr_codigo__4affa4_idx'), models.Index(fields=['anio'], name='plan_arbitr_anio_18dd36_idx'), models.Index(fields=['mes'], name='plan_arbitr_mes_89faae_idx'), models.Index(fields=['empresa', 'codigo_rubro'], name='plan_arbitr_empresa_0214f0_idx'), models.Index(fields=['empresa', 'anio', 'mes'], name='plan_arbitr_empresa_f704ff_idx')],
                'unique_together': {('empresa', 'codigo_rubro', 'anio', 'mes')},
            },
        ),
    ]
