# Generated by Django 5.2.1 on 2025-08-13 14:02

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0025_planarbitrio'),
    ]

    operations = [
        migrations.RunSQL(
            # SQL para actualizar la tabla existente
            """
            -- Asegurar que la tabla tenga la estructura correcta
            ALTER TABLE planarbitio 
            MODIFY COLUMN empresa CHAR(4) COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
            MODIFY COLUMN rubro CHAR(3) COLLATE utf8mb4_0900_ai_ci DEFAULT '',
            MODIFY COLUMN ano DECIMAL(4,0) DEFAULT NULL,
            MODIFY COLUMN codigo CHAR(20) COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT '',
            MODIFY COLUMN descripcion CHAR(200) COLLATE utf8mb4_0900_ai_ci DEFAULT '',
            MODIFY COLUMN minimo DECIMAL(12,2) DEFAULT 0.00,
            MODIFY COLUMN maximo DECIMAL(12,2) DEFAULT 0.00,
            MODIFY COLUMN valor DECIMAL(12,2) DEFAULT 0.00;
            """,
            # SQL para revertir los cambios
            """
            -- No hay reversión necesaria ya que solo estamos asegurando la estructura
            """
        ),
    ]
