# Generated by Django 5.2.1 on 2025-08-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0026_auto_20250813_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Año',
                'verbose_name_plural': 'Años',
                'db_table': 'anos',
                'ordering': ['ano'],
            },
        ),
        migrations.AlterModelOptions(
            name='planarbitrio',
            options={'ordering': ['-ano', 'codigo'], 'verbose_name': 'Plan de Arbitrio', 'verbose_name_plural': 'Planes de Arbitrio'},
        ),
        migrations.RemoveIndex(
            model_name='planarbitrio',
            name='plan_arbitr_codigo__4affa4_idx',
        ),
        migrations.RemoveIndex(
            model_name='planarbitrio',
            name='plan_arbitr_anio_18dd36_idx',
        ),
        migrations.RemoveIndex(
            model_name='planarbitrio',
            name='plan_arbitr_mes_89faae_idx',
        ),
        migrations.RemoveIndex(
            model_name='planarbitrio',
            name='plan_arbitr_empresa_0214f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='planarbitrio',
            name='plan_arbitr_empresa_f704ff_idx',
        ),
        migrations.RenameIndex(
            model_name='planarbitrio',
            new_name='planarbitio_empresa_4c94a3_idx',
            old_name='plan_arbitr_empresa_d2f2be_idx',
        ),
        migrations.AlterUniqueTogether(
            name='planarbitrio',
            unique_together={('empresa', 'codigo')},
        ),
        migrations.AddField(
            model_name='planarbitrio',
            name='ano',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='planarbitrio',
            name='codigo',
            field=models.CharField(db_collation='utf8mb4_0900_ai_ci', default='', max_length=20, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='planarbitrio',
            name='descripcion',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='planarbitrio',
            name='maximo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Máximo'),
        ),
        migrations.AddField(
            model_name='planarbitrio',
            name='minimo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Mínimo'),
        ),
        migrations.AddField(
            model_name='planarbitrio',
            name='rubro',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=3, null=True, verbose_name='Rubro'),
        ),
        migrations.AddField(
            model_name='planarbitrio',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='descripcion_rubro',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=200, null=True, verbose_name='Descripción del Rubro'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='empresa',
            field=models.CharField(db_collation='utf8mb4_0900_ai_ci', default='', max_length=4, verbose_name='Empresa'),
        ),
        migrations.AddIndex(
            model_name='planarbitrio',
            index=models.Index(fields=['codigo'], name='planarbitio_codigo_96736d_idx'),
        ),
        migrations.AddIndex(
            model_name='planarbitrio',
            index=models.Index(fields=['ano'], name='planarbitio_ano_035639_idx'),
        ),
        migrations.AddIndex(
            model_name='planarbitrio',
            index=models.Index(fields=['empresa', 'codigo'], name='planarbitio_empresa_dfe852_idx'),
        ),
        migrations.AlterModelTable(
            name='planarbitrio',
            table='planarbitio',
        ),
        migrations.AddIndex(
            model_name='anos',
            index=models.Index(fields=['ano'], name='anos_ano_833c25_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='anos',
            unique_together={('ano',)},
        ),
        migrations.RemoveField(
            model_name='planarbitrio',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='planarbitrio',
            name='codigo_rubro',
        ),
        migrations.RemoveField(
            model_name='planarbitrio',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='planarbitrio',
            name='factor_correccion',
        ),
        migrations.RemoveField(
            model_name='planarbitrio',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='planarbitrio',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='planarbitrio',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='planarbitrio',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='planarbitrio',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='planarbitrio',
            name='valor_base',
        ),
        migrations.RemoveField(
            model_name='planarbitrio',
            name='valor_final',
        ),
    ]
