# Generated by Django 5.2.1 on 2025-08-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0029_update_plan_arbitrio_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(db_collation='utf8mb4_0900_ai_ci', default='', max_length=4, verbose_name='Empresa')),
                ('rubro', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=3, null=True, verbose_name='Rubro')),
                ('cod_tarifa', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=20, null=True, verbose_name='Código de Tarifa')),
                ('ano', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Año')),
                ('descripcion', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=200, null=True, verbose_name='Descripción')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor')),
                ('frecuencia', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=1, null=True, verbose_name='Frecuencia')),
                ('tipo', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=1, null=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
                'db_table': 'tarifas',
                'ordering': ['-ano', 'cod_tarifa'],
                'indexes': [models.Index(fields=['empresa'], name='tarifas_empresa_19bcf8_idx'), models.Index(fields=['rubro'], name='tarifas_rubro_fcd066_idx'), models.Index(fields=['cod_tarifa'], name='tarifas_cod_tar_f5b9cc_idx'), models.Index(fields=['ano'], name='tarifas_ano_9234e3_idx'), models.Index(fields=['empresa', 'ano'], name='tarifas_empresa_187bc2_idx')],
                'unique_together': {('empresa', 'ano')},
            },
        ),
    ]
