# Generated by Django 5.2.1 on 2025-08-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0030_tarifas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anos',
            options={'verbose_name': 'Año', 'verbose_name_plural': 'Años'},
        ),
        migrations.AlterModelOptions(
            name='tarifas',
            options={'verbose_name': 'Tarifa', 'verbose_name_plural': 'Tarifas'},
        ),
        migrations.RemoveIndex(
            model_name='anos',
            name='anos_ano_833c25_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarifas',
            name='tarifas_empresa_19bcf8_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarifas',
            name='tarifas_rubro_fcd066_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarifas',
            name='tarifas_cod_tar_f5b9cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarifas',
            name='tarifas_ano_9234e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarifas',
            name='tarifas_empresa_187bc2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='anos',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='anos',
            name='ano',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, primary_key=True, serialize=False, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='frecuencia',
            field=models.CharField(blank=True, choices=[('A', 'Anual'), ('M', 'Mensual')], db_collation='utf8mb4_0900_ai_ci', max_length=1, null=True, verbose_name='Frecuencia'),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='tipo',
            field=models.CharField(blank=True, choices=[('F', 'Fija'), ('V', 'Variable')], db_collation='utf8mb4_0900_ai_ci', max_length=1, null=True, verbose_name='Tipo'),
        ),
        migrations.RemoveField(
            model_name='anos',
            name='id',
        ),
    ]
