# Generated by Django 5.2.1 on 2025-08-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0031_alter_anos_options_alter_tarifas_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubro',
            name='valor',
        ),
        migrations.AlterField(
            model_name='rubro',
            name='codigo',
            field=models.CharField(db_collation='utf8mb4_0900_ai_ci', default='', max_length=4, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='cuenta',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=20, null=True, verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='cuntarez',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=20, null=True, verbose_name='Cuenta Rezago'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='descripcion',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='empresa',
            field=models.CharField(db_collation='utf8mb4_0900_ai_ci', default='', max_length=4, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='tipo',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=1, null=True, verbose_name='Tipo'),
        ),
    ]
