# Generated by Django 5.2.1 on 2025-08-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0032_remove_rubro_valor_alter_rubro_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifas',
            name='cod_tarifa',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=4, null=True, verbose_name='Código de Tarifa'),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='rubro',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=4, null=True, verbose_name='Rubro'),
        ),
    ]
