# Generated by Django 5.2.1 on 2025-08-19 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0033_alter_tarifas_cod_tarifa_alter_tarifas_rubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='planarbitrio',
            name='cod_tarifa',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=20, null=True, verbose_name='Código de Tarifa'),
        ),
    ]
