# Generated by Django 5.2.1 on 2025-08-19 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0034_planarbitrio_cod_tarifa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tarifas',
            unique_together={('empresa', 'rubro', 'ano', 'cod_tarifa')},
        ),
    ]
