# Generated by Django 5.2.1 on 2025-08-26 02:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0035_alter_tarifas_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracionVolumen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=4, verbose_name='Empresa')),
                ('rtm', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=16, verbose_name='RTM')),
                ('expe', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=12, verbose_name='Expediente')),
                ('ano', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Año')),
                ('mes', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Mes')),
                ('tipo', models.CharField(choices=[('1', 'Declaración Normal'), ('2', 'Declaración por Apertura')], db_collation='latin1_swedish_ci', max_length=1, verbose_name='Tipo')),
                ('ventai', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Ventas Rubro Producción')),
                ('ventac', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Ventas Mercadería')),
                ('ventas', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Ventas por Servicios')),
                ('valorexcento', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valores Exentos')),
                ('cocontrolado', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Ventas Productos Controlados')),
                ('unidad', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=10, verbose_name='Unidad')),
                ('factor', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Factor')),
                ('base_calculo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Base para Cálculo')),
                ('fecha_declaracion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Declaración')),
                ('usuario', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=10, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Declaración de Volumen',
                'verbose_name_plural': 'Declaraciones de Volumen',
                'db_table': 'declaracion_volumen',
            },
        ),
        migrations.CreateModel(
            name='TarifasICS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('idneg', models.IntegerField(default=0, verbose_name='ID Negocio')),
                ('rtm', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=20, verbose_name='RTM')),
                ('expe', models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', max_length=10, null=True, verbose_name='Expediente')),
                ('cod_tarifa', models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', max_length=4, null=True, verbose_name='Código de Tarifa')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01, message='El valor debe ser mayor a 0')], verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Tarifa ICS',
                'verbose_name_plural': 'Tarifas ICS',
                'db_table': 'tarifasics',
            },
        ),
        migrations.RemoveIndex(
            model_name='planarbitrio',
            name='planarbitio_empresa_dfe852_idx',
        ),
        migrations.AlterUniqueTogether(
            name='planarbitrio',
            unique_together={('empresa', 'rubro', 'cod_tarifa', 'ano', 'codigo')},
        ),
        migrations.AddField(
            model_name='tarifas',
            name='categoria',
            field=models.CharField(blank=True, choices=[('D', 'Doméstico'), ('C', 'Comercial')], db_collation='utf8mb4_0900_ai_ci', max_length=1, null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='celular',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='cod_tarifa',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=4, null=True, verbose_name='Código de Tarifa'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='rubro',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=4, null=True, verbose_name='Rubro'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor'),
        ),
        migrations.AddIndex(
            model_name='planarbitrio',
            index=models.Index(fields=['rubro'], name='planarbitio_rubro_22a028_idx'),
        ),
        migrations.AddIndex(
            model_name='planarbitrio',
            index=models.Index(fields=['cod_tarifa'], name='planarbitio_cod_tar_8811df_idx'),
        ),
        migrations.AddIndex(
            model_name='planarbitrio',
            index=models.Index(fields=['empresa', 'rubro', 'cod_tarifa', 'ano', 'codigo'], name='planarbitio_empresa_31b064_idx'),
        ),
        migrations.AddIndex(
            model_name='tarifas',
            index=models.Index(fields=['empresa'], name='tarifas_empresa_19bcf8_idx'),
        ),
        migrations.AddIndex(
            model_name='tarifas',
            index=models.Index(fields=['rubro'], name='tarifas_rubro_fcd066_idx'),
        ),
        migrations.AddIndex(
            model_name='tarifas',
            index=models.Index(fields=['ano'], name='tarifas_ano_9234e3_idx'),
        ),
        migrations.AddIndex(
            model_name='tarifas',
            index=models.Index(fields=['cod_tarifa'], name='tarifas_cod_tar_f5b9cc_idx'),
        ),
        migrations.AddIndex(
            model_name='tarifas',
            index=models.Index(fields=['empresa', 'rubro', 'ano', 'cod_tarifa'], name='tarifas_empresa_13559d_idx'),
        ),
        migrations.AddIndex(
            model_name='declaracionvolumen',
            index=models.Index(fields=['empresa'], name='declaracion_empresa_4cd739_idx'),
        ),
        migrations.AddIndex(
            model_name='declaracionvolumen',
            index=models.Index(fields=['rtm'], name='declaracion_rtm_d1bc7f_idx'),
        ),
        migrations.AddIndex(
            model_name='declaracionvolumen',
            index=models.Index(fields=['expe'], name='declaracion_expe_a17eab_idx'),
        ),
        migrations.AddIndex(
            model_name='declaracionvolumen',
            index=models.Index(fields=['ano'], name='declaracion_ano_64d437_idx'),
        ),
        migrations.AddIndex(
            model_name='declaracionvolumen',
            index=models.Index(fields=['mes'], name='declaracion_mes_edaaf0_idx'),
        ),
        migrations.AddIndex(
            model_name='declaracionvolumen',
            index=models.Index(fields=['empresa', 'rtm', 'expe'], name='declaracion_empresa_51c3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='declaracionvolumen',
            index=models.Index(fields=['empresa', 'ano', 'mes'], name='declaracion_empresa_e61815_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='declaracionvolumen',
            unique_together={('empresa', 'rtm', 'expe', 'ano', 'mes')},
        ),
        migrations.AddIndex(
            model_name='tarifasics',
            index=models.Index(fields=['rtm'], name='tarifasics_idx1'),
        ),
        migrations.AddIndex(
            model_name='tarifasics',
            index=models.Index(fields=['expe'], name='tarifasics_idx2'),
        ),
        migrations.AddIndex(
            model_name='tarifasics',
            index=models.Index(fields=['cod_tarifa'], name='tarifasics_idx3'),
        ),
        migrations.AddIndex(
            model_name='tarifasics',
            index=models.Index(fields=['idneg'], name='tarifasics_idx5'),
        ),
        migrations.RemoveField(
            model_name='planarbitrio',
            name='descripcion_rubro',
        ),
    ]
