# Generated by Django 5.2.1 on 2025-09-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0036_declaracionvolumen_tarifasics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarifasImptoics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(db_collation='utf8mb4_0900_ai_ci', default='', max_length=1, verbose_name='Categoría')),
                ('descripcion', models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=200, null=True, verbose_name='Descripción')),
                ('codigo', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=1, null=True, verbose_name='Código')),
                ('rango1', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Rango 1')),
                ('rango2', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Rango 2')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Tarifa Imptoics',
                'verbose_name_plural': 'Tarifas Imptoics',
                'db_table': 'tarifasimptoics',
                'ordering': ['categoria', 'rango1'],
            },
        ),
        migrations.AlterModelOptions(
            name='planarbitrio',
            options={'verbose_name': 'Plan de Arbitrio', 'verbose_name_plural': 'Planes de Arbitrio'},
        ),
        migrations.RemoveIndex(
            model_name='declaracionvolumen',
            name='declaracion_empresa_4cd739_idx',
        ),
        migrations.RemoveIndex(
            model_name='declaracionvolumen',
            name='declaracion_mes_edaaf0_idx',
        ),
        migrations.RemoveIndex(
            model_name='declaracionvolumen',
            name='declaracion_empresa_51c3c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='declaracionvolumen',
            name='declaracion_empresa_e61815_idx',
        ),
        migrations.RemoveIndex(
            model_name='planarbitrio',
            name='planarbitio_codigo_96736d_idx',
        ),
        migrations.RemoveIndex(
            model_name='planarbitrio',
            name='planarbitio_empresa_31b064_idx',
        ),
        migrations.RenameIndex(
            model_name='declaracionvolumen',
            new_name='declara_idx1',
            old_name='declaracion_rtm_d1bc7f_idx',
        ),
        migrations.RenameIndex(
            model_name='declaracionvolumen',
            new_name='declara_idx2',
            old_name='declaracion_expe_a17eab_idx',
        ),
        migrations.RenameIndex(
            model_name='declaracionvolumen',
            new_name='declara_idx3',
            old_name='declaracion_ano_64d437_idx',
        ),
        migrations.RenameIndex(
            model_name='planarbitrio',
            new_name='planarbitio_empresa_idx',
            old_name='planarbitio_empresa_4c94a3_idx',
        ),
        migrations.RenameIndex(
            model_name='planarbitrio',
            new_name='planarbitio_rubro_idx',
            old_name='planarbitio_rubro_22a028_idx',
        ),
        migrations.RenameIndex(
            model_name='planarbitrio',
            new_name='planarbitio_cod_tarifa_idx',
            old_name='planarbitio_cod_tar_8811df_idx',
        ),
        migrations.RenameIndex(
            model_name='planarbitrio',
            new_name='planarbitio_ano_idx',
            old_name='planarbitio_ano_035639_idx',
        ),
        migrations.AlterUniqueTogether(
            name='declaracionvolumen',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='declaracionvolumen',
            name='idneg',
            field=models.IntegerField(default=0, verbose_name='ID Negocio'),
        ),
        migrations.AddField(
            model_name='declaracionvolumen',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Impuesto Calculado'),
        ),
        migrations.AddField(
            model_name='tarifasics',
            name='rubro',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', max_length=4, null=True, verbose_name='Rubro'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='ano',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='cocontrolado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Ventas Productos Controlados'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='expe',
            field=models.CharField(db_collation='latin1_swedish_ci', default='', max_length=10, verbose_name='Expediente'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='factor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Factor'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='mes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='rtm',
            field=models.CharField(db_collation='latin1_swedish_ci', default='', max_length=20, verbose_name='RTM'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='tipo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='unidad',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='valorexcento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valores Exentos'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='ventac',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Ventas Mercadería'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='ventai',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Ventas Rubro Producción'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='ventas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Ventas por Servicios'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='cod_tarifa',
            field=models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=4, null=True, verbose_name='Código Tarifa'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='descripcion',
            field=models.CharField(db_collation='utf8mb4_0900_ai_ci', default='', max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='maximo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Máximo'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='minimo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Mínimo'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='rubro',
            field=models.CharField(db_collation='utf8mb4_0900_ai_ci', default='', max_length=4, verbose_name='Rubro'),
        ),
        migrations.AddIndex(
            model_name='declaracionvolumen',
            index=models.Index(fields=['idneg'], name='declara_idx5'),
        ),
        migrations.AddIndex(
            model_name='planarbitrio',
            index=models.Index(fields=['empresa', 'rubro'], name='planarbitio_empresa_rubro_idx'),
        ),
        migrations.AlterModelTable(
            name='declaracionvolumen',
            table='declara',
        ),
        migrations.RemoveField(
            model_name='declaracionvolumen',
            name='base_calculo',
        ),
        migrations.RemoveField(
            model_name='declaracionvolumen',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='declaracionvolumen',
            name='fecha_declaracion',
        ),
        migrations.RemoveField(
            model_name='declaracionvolumen',
            name='usuario',
        ),
    ]
