# Generated by Django 5.2.1 on 2025-09-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0037_tarifasimptoics_alter_planarbitrio_options_and_more'),
    ]

    operations = [
        # Agregar campo empresa a TarifasICS
        migrations.AddField(
            model_name='tarifasics',
            name='empresa',
            field=models.CharField(
                blank=True, 
                db_collation='latin1_swedish_ci', 
                max_length=4, 
                null=True, 
                verbose_name='Empresa'
            ),
        ),
        # Agregar restricción única para empresa, rtm, expe, cod_tarifa
        migrations.AddConstraint(
            model_name='tarifasics',
            constraint=models.UniqueConstraint(
                fields=['empresa', 'rtm', 'expe', 'cod_tarifa'], 
                name='tarifasics_idx4'
            ),
        ),
    ]
