# Generated by Django 5.2.1 on 2025-09-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0037_tarifasimptoics_alter_planarbitrio_options_and_more'),
        ('tributario_app', '0038_update_tarifasics_model'),
        ('tributario_app', '0039_add_multadecla_field'),
    ]

    operations = [
    ]
