# Generated by Django 5.2.1 on 2025-10-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0040_merge_20250916_2236'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE `tasasdecla` ADD COLUMN `tipo` CHAR(1) COLLATE latin1_swedish_ci DEFAULT NULL;",
            reverse_sql="ALTER TABLE `tasasdecla` DROP COLUMN `tipo`;"
        ),
    ]
