# Generated by Django 5.2.1 on 2025-10-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0041_add_tipo_to_tasasdecla'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE `tasasdecla` ADD COLUMN `tipota` CHAR(1) COLLATE latin1_swedish_ci DEFAULT '';",
            reverse_sql="ALTER TABLE `tasasdecla` DROP COLUMN `tipota`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `tasasdecla` DROP INDEX `tasasdecla_idx4`;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "ALTER TABLE `tasasdecla` ADD UNIQUE KEY `tasasdecla_idx4` USING BTREE (`empresa`, `rtm`, `expe`, `ano`, `rubro`, `nodecla`);",
            reverse_sql=migrations.RunSQL.noop
        ),
    ]










































