# Generated by Django 5.2.1 on 2025-10-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0045_force_sync_tipota'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoEmpreNu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=6, null=True, verbose_name='Empresa')),
                ('ano', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Año')),
                ('nudecla', models.DecimalField(decimal_places=0, default=0, max_digits=11, verbose_name='Número de Declaración')),
                ('nopermiso', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Número de Permiso de Operación')),
                ('noplanes', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Número de Planes')),
            ],
            options={
                'verbose_name': 'Año Empresa Numeración',
                'verbose_name_plural': 'Años Empresa Numeración',
                'db_table': 'anoemprenu',
                'ordering': ['-ano', 'empresa'],
            },
        ),
        migrations.CreateModel(
            name='TasasDecla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=4, null=True, verbose_name='Empresa')),
                ('idneg', models.IntegerField(default=0, verbose_name='ID Negocio')),
                ('rtm', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=20, verbose_name='RTM')),
                ('expe', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=10, verbose_name='Expediente')),
                ('nodecla', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=20, verbose_name='Número de Declaración')),
                ('ano', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Año')),
                ('rubro', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=6, verbose_name='Rubro')),
                ('cod_tarifa', models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=4, null=True, verbose_name='Código de Tarifa')),
                ('frecuencia', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=1, verbose_name='Frecuencia')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor')),
                ('cuenta', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=20, verbose_name='Cuenta')),
                ('cuentarez', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=20, verbose_name='Cuenta Rezago')),
                ('tipota', models.CharField(db_collation='latin1_swedish_ci', db_column='tipota', default='', max_length=1, verbose_name='Tipo Tasa')),
            ],
            options={
                'verbose_name': 'Tasa de Declaración',
                'verbose_name_plural': 'Tasas de Declaraciones',
                'db_table': 'tasasdecla',
            },
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='anos',
            options={'managed': False, 'ordering': ['-ano'], 'verbose_name': 'Año', 'verbose_name_plural': 'Años'},
        ),
        migrations.AlterModelOptions(
            name='oficina',
            options={'verbose_name': 'Oficina', 'verbose_name_plural': 'Oficinas'},
        ),
        migrations.AlterModelOptions(
            name='planarbitrio',
            options={'ordering': ['-ano', 'codigo'], 'verbose_name': 'Plan de Arbitrio', 'verbose_name_plural': 'Planes de Arbitrio'},
        ),
        migrations.AlterModelOptions(
            name='rubro',
            options={'verbose_name': 'Rubro', 'verbose_name_plural': 'Rubros'},
        ),
        migrations.AlterModelOptions(
            name='tarifas',
            options={'ordering': ['-ano', 'cod_tarifa'], 'verbose_name': 'Tarifa', 'verbose_name_plural': 'Tarifas'},
        ),
        migrations.RemoveConstraint(
            model_name='tarifasics',
            name='tarifasics_idx4',
        ),
        migrations.RemoveIndex(
            model_name='planarbitrio',
            name='planarbitio_empresa_idx',
        ),
        migrations.RemoveIndex(
            model_name='planarbitrio',
            name='planarbitio_ano_idx',
        ),
        migrations.RemoveIndex(
            model_name='planarbitrio',
            name='planarbitio_rubro_idx',
        ),
        migrations.RemoveIndex(
            model_name='planarbitrio',
            name='planarbitio_cod_tarifa_idx',
        ),
        migrations.RemoveIndex(
            model_name='planarbitrio',
            name='planarbitio_empresa_rubro_idx',
        ),
        migrations.RemoveIndex(
            model_name='rubro',
            name='rubros_empresa_2ba792_idx',
        ),
        migrations.RemoveIndex(
            model_name='rubro',
            name='rubros_codigo_413d1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='rubro',
            name='rubros_empresa_37915f_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarifas',
            name='tarifas_empresa_19bcf8_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarifas',
            name='tarifas_rubro_fcd066_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarifas',
            name='tarifas_ano_9234e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarifas',
            name='tarifas_cod_tar_f5b9cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='tarifas',
            name='tarifas_empresa_13559d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='declaracionvolumen',
            unique_together={('empresa', 'rtm', 'expe', 'ano')},
        ),
        migrations.AlterUniqueTogether(
            name='negocio',
            unique_together={('empresa', 'rtm', 'expe')},
        ),
        migrations.RemoveField(
            model_name='pagovariostemp',
            name='Direccion',
        ),
        migrations.RemoveField(
            model_name='rubro',
            name='cuntarez',
        ),
        migrations.AlterUniqueTogether(
            name='tarifas',
            unique_together={('empresa', 'ano', 'cod_tarifa')},
        ),
        migrations.AddField(
            model_name='actividad',
            name='cuentarez',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=20, null=True, verbose_name='Cuenta Rezago'),
        ),
        migrations.AddField(
            model_name='declaracionvolumen',
            name='ajuste',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Ajuste'),
        ),
        migrations.AddField(
            model_name='declaracionvolumen',
            name='controlado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Productos Controlados'),
        ),
        migrations.AddField(
            model_name='declaracionvolumen',
            name='empresa',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=4, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='declaracionvolumen',
            name='fechssys',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Sistema'),
        ),
        migrations.AddField(
            model_name='declaracionvolumen',
            name='nodecla',
            field=models.CharField(db_collation='latin1_swedish_ci', default='', max_length=20, verbose_name='Número de Declaración'),
        ),
        migrations.AddField(
            model_name='declaracionvolumen',
            name='usuario',
            field=models.CharField(db_collation='latin1_swedish_ci', default='', max_length=50, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='identificacion',
            name='fechanac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='empresa',
            field=models.CharField(db_collation='latin1_swedish_ci', default='', max_length=4, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='rubro',
            name='cuentarez',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=20, verbose_name='Cuenta Rezago'),
        ),
        migrations.AddField(
            model_name='tarifas',
            name='tipomodulo',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=1, null=True, verbose_name='Tipo Módulo'),
        ),
        migrations.AddField(
            model_name='tarifasics',
            name='cuenta',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', max_length=20, verbose_name='Cuenta'),
        ),
        migrations.AddField(
            model_name='tarifasics',
            name='cuentarez',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', max_length=20, verbose_name='Cuenta Rezago'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='codigo',
            field=models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='empresa',
            field=models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=4, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='ano',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='mes',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='multadecla',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Multa Declaración'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='valorexcento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Valor Exento'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='ventac',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Ventas Mercadería'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='ventai',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Ventas Rubro Producción'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='ventas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Ventas por Servicios'),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='apellidos',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=30, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='identidad',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=18, unique=True, verbose_name='Identidad'),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='nombres',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=30, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='catastral',
            field=models.CharField(db_collation='latin1_swedish_ci', default='', max_length=17, verbose_name='Catastral'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='categoria',
            field=models.CharField(db_collation='latin1_swedish_ci', default='01', max_length=2, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='estatus',
            field=models.CharField(db_collation='latin1_swedish_ci', default='A', max_length=1, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='expe',
            field=models.CharField(db_collation='latin1_swedish_ci', default='', max_length=12, verbose_name='Expediente'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='identidad',
            field=models.CharField(db_collation='latin1_swedish_ci', default='', max_length=20, verbose_name='Identidad'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='nombrenego',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=100, verbose_name='Nombre Negocio'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='rtm',
            field=models.CharField(db_collation='latin1_swedish_ci', default='', max_length=16, verbose_name='RTM'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='socios',
            field=models.CharField(db_collation='latin1_swedish_ci', default='', max_length=250, verbose_name='Socios'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='telefono',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='norecibos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='norecibos',
            name='numero',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='norecibos',
            name='solvencia',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Solvencia'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='codigo',
            field=models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='descripcion',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='empresa',
            field=models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=4, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='Rtm',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=20, verbose_name='RTM'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='Tipofa',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=1, verbose_name='Tipo de Factura'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='aplicado',
            field=models.CharField(db_collation='latin1_swedish_ci', default='0', max_length=1, verbose_name='Aplicado'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='banco',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=3, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='cajero',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=20, null=True, verbose_name='Cajero'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='categoria',
            field=models.CharField(db_collation='latin1_swedish_ci', default='', max_length=2, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='codigo',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=16, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='comentario',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=500, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='descripcion',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='direccion',
            field=models.CharField(db_collation='latin1_swedish_ci', default=' ', max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='empresa',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=6, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='facturadora',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=45, null=True, verbose_name='Facturadora'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='fecha_solv',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Solvencia'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='identidad',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=31, null=True, verbose_name='Identidad'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='nombre',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=150, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='oficina',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=20, null=True, verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='prima',
            field=models.CharField(db_collation='latin1_swedish_ci', default='', max_length=1, verbose_name='Prima'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='recibo',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Recibo'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='referencia',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=20, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='rtn',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=20, null=True, verbose_name='RTN'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='sexo',
            field=models.CharField(db_collation='latin1_swedish_ci', default='', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='traslado',
            field=models.CharField(db_collation='latin1_swedish_ci', default='0', max_length=1, verbose_name='Traslado'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='usuario',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', max_length=30, null=True, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='cod_tarifa',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=4, null=True, verbose_name='Código de Tarifa'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='descripcion',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='maximo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Máximo'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='minimo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Mínimo'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='rubro',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=6, null=True, verbose_name='Rubro'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='codigo',
            field=models.CharField(db_collation='utf8mb4_0900_ai_ci', default='', max_length=6, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='cuenta',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=20, verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='descripcion',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='tipo',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='cod_tarifa',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=20, null=True, verbose_name='Código de Tarifa'),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='frecuencia',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=1, null=True, verbose_name='Frecuencia'),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='rubro',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=6, null=True, verbose_name='Rubro'),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='tipo',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', max_length=1, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tarifasics',
            name='rubro',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', max_length=6, null=True, verbose_name='Rubro'),
        ),
        migrations.AlterField(
            model_name='tarifasics',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='tarifasimptoics',
            name='categoria',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=1, null=True, verbose_name='Categoría'),
        ),
        migrations.AddIndex(
            model_name='pagovariostemp',
            index=models.Index(fields=['recibo'], name='pagovariost_recibo_430425_idx'),
        ),
        migrations.AddIndex(
            model_name='pagovariostemp',
            index=models.Index(fields=['solvencia'], name='pagovariost_solvenc_3a2bd3_idx'),
        ),
        migrations.AddIndex(
            model_name='pagovariostemp',
            index=models.Index(fields=['codigo'], name='pagovariost_codigo_6d6210_idx'),
        ),
        migrations.AddIndex(
            model_name='pagovariostemp',
            index=models.Index(fields=['fecha'], name='pagovariost_fecha_ac92ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='tarifasics',
            constraint=models.UniqueConstraint(fields=('empresa', 'rtm', 'expe', 'rubro'), name='tarifasics_idx4'),
        ),
        migrations.AddIndex(
            model_name='tasasdecla',
            index=models.Index(fields=['rtm'], name='tasasdecla_idx1'),
        ),
        migrations.AddIndex(
            model_name='tasasdecla',
            index=models.Index(fields=['expe'], name='tasasdecla_idx2'),
        ),
        migrations.AddIndex(
            model_name='tasasdecla',
            index=models.Index(fields=['cod_tarifa'], name='tasasdecla_idx3'),
        ),
        migrations.AddIndex(
            model_name='tasasdecla',
            index=models.Index(fields=['idneg'], name='tasasdecla_idx5'),
        ),
        migrations.AlterUniqueTogether(
            name='tasasdecla',
            unique_together={('empresa', 'rtm', 'expe', 'ano', 'rubro', 'nodecla')},
        ),
        migrations.RemoveField(
            model_name='declaracionvolumen',
            name='cocontrolado',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='empre',
        ),
        migrations.RemoveField(
            model_name='tarifas',
            name='categoria',
        ),
    ]
