# Generated by Django 5.2.1 on 2025-10-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0046_anoemprenu_tasasdecla_delete_municipio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracionvolumen',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='Valor Base (Ventas Totales)'),
        ),
    ]
