# Generated by Django 5.2.1 on 2025-11-02 22:05
# Corregido: transaccionesics pertenece a tributario, no tributario_app.
# Se usa RunPython para alterar la tabla sin depender del estado del modelo.

from django.db import migrations


def alter_rtm_transaccionesics(apps, schema_editor):
    """Aumentar tamaño de columna rtm en tabla transaccionesics (modelo en paquete tributario)."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE transaccionesics
            MODIFY COLUMN rtm VARCHAR(30) COLLATE latin1_swedish_ci NOT NULL DEFAULT ''
        """)


def reverse_alter_rtm(apps, schema_editor):
    """Revertir: rtm a VARCHAR(20) si se deshace la migración."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE transaccionesics
            MODIFY COLUMN rtm VARCHAR(20) COLLATE latin1_swedish_ci NOT NULL DEFAULT ''
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0047_declaracionvolumen_valor_base'),
    ]

    operations = [
        migrations.RunPython(alter_rtm_transaccionesics, reverse_alter_rtm),
    ]
