# Generated by Django 5.2.1 on 2025-11-02

from django.db import migrations


def add_cuentarec_column(apps, schema_editor):
    """Agregar columna cuentarec a la tabla actividad si no existe"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Verificar si la columna ya existe
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'actividad' 
            AND COLUMN_NAME = 'cuentarec'
        """)
        exists = cursor.fetchone()[0] > 0
        
        if not exists:
            # Agregar columna cuentarec
            cursor.execute("""
                ALTER TABLE actividad 
                ADD COLUMN cuentarec CHAR(20) COLLATE utf8mb4_0900_ai_ci DEFAULT '' 
                AFTER cuentarez
            """)
        
        # Asegurar que cuentarez no permita NULL
        cursor.execute("""
            ALTER TABLE actividad 
            MODIFY COLUMN cuentarez CHAR(20) COLLATE utf8mb4_0900_ai_ci DEFAULT '' NOT NULL
        """)


def remove_cuentarec_column(apps, schema_editor):
    """Eliminar columna cuentarec (rollback)"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'actividad' 
            AND COLUMN_NAME = 'cuentarec'
        """)
        exists = cursor.fetchone()[0] > 0
        
        if exists:
            cursor.execute("ALTER TABLE actividad DROP COLUMN cuentarec")


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0048_aumentar_tamano_rtm_transaccionesics'),
    ]

    operations = [
        migrations.RunPython(
            add_cuentarec_column,
            reverse_code=remove_cuentarec_column
        ),
    ]

