# Generated by Django 5.2.1 on 2025-12-XX

from django.db import migrations


def add_cuentaint_column(apps, schema_editor):
    """Agregar columna cuentaint a la tabla actividad si no existe"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Verificar si la columna ya existe
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'actividad' 
            AND COLUMN_NAME = 'cuentaint'
        """)
        exists = cursor.fetchone()[0] > 0
        
        if not exists:
            # Agregar columna cuentaint después de cuentarec
            cursor.execute("""
                ALTER TABLE actividad 
                ADD COLUMN cuentaint CHAR(20) COLLATE utf8mb4_0900_ai_ci DEFAULT '' 
                AFTER cuentarec
            """)


def remove_cuentaint_column(apps, schema_editor):
    """Eliminar columna cuentaint (rollback)"""
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'actividad' 
            AND COLUMN_NAME = 'cuentaint'
        """)
        exists = cursor.fetchone()[0] > 0
        
        if exists:
            cursor.execute("ALTER TABLE actividad DROP COLUMN cuentaint")


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0049_add_cuentarec_to_actividad'),
    ]

    operations = [
        migrations.RunPython(
            add_cuentaint_column,
            reverse_code=remove_cuentaint_column
        ),
    ]














