# Generated by Django 4.2.27 on 2026-04-14 22:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0050_add_cuentaint_to_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosTributarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(db_collation='latin1_swedish_ci', default='GLOB', help_text="Use 'GLOB' para aplicar a todos los municipios. Un código de empresa específico sobrescribe el global.", max_length=4, verbose_name='Empresa (GLOB=Global)')),
                ('tipo_parametro', models.CharField(choices=[('AM', 'Amnistía Tributaria'), ('TE', 'Descuento Tercera Edad'), ('CE', 'Descuento Cuarta Edad'), ('PA', 'Descuento Pago Anual Anticipado'), ('RM', 'Tasa de Recargo Moratorio')], max_length=2, verbose_name='Tipo de Parámetro')),
                ('ano_vigencia', models.IntegerField(help_text='Año fiscal al que aplica este parámetro', verbose_name='Año de Vigencia')),
                ('descripcion', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=200, verbose_name='Descripción')),
                ('numero_decreto', models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', help_text='Ej: Decreto No. 123-2024 — base legal del beneficio', max_length=50, verbose_name='Número de Decreto')),
                ('fecha_inicio', models.DateField(blank=True, help_text='Inicio del periodo durante el cual el beneficio está activo', null=True, verbose_name='Fecha de Inicio de Vigencia')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fin del periodo de vigencia del beneficio. Nulo = sin límite de vigencia', null=True, verbose_name='Fecha de Fin de Vigencia')),
                ('fecha_corte', models.DateField(blank=True, help_text='Los cargos vencidos HASTA esta fecha aplican el beneficio (corte de deuda)', null=True, verbose_name='Fecha de Corte de Saldos')),
                ('aplica_recargos', models.BooleanField(default=False, help_text='Si True, condona/descuenta rubros cuyo código inicia con R', verbose_name='Aplica a Recargos (rubros R*)')),
                ('aplica_intereses', models.BooleanField(default=False, verbose_name='Aplica a Intereses Moratorios')),
                ('aplica_saldo_impuesto', models.BooleanField(default=False, verbose_name='Aplica descuento sobre saldo de impuesto/tasa')),
                ('porcentaje_condonacion', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='100 = condonación total; menores = parcial', max_digits=5, verbose_name='% Condonación de Recargos/Intereses')),
                ('porcentaje_descuento_saldo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='% Descuento sobre Saldo de Impuesto')),
                ('meses_anticipacion', models.IntegerField(default=4, help_text='Mínimo de meses de anticipación para descuento de pago anual', verbose_name='Meses de Anticipación Requeridos')),
                ('porcentaje_descuento_anual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='% Descuento Pago Anual')),
                ('tasa_recargo_mensual', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Ej: 2.5 = 2.5% mensual sobre saldo vencido', max_digits=7, verbose_name='Tasa Mensual de Recargo Moratorio (%)')),
                ('recargo_maximo_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 = sin límite', max_digits=7, verbose_name='Recargo Máximo (%)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('usuario_crea', models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', max_length=50, verbose_name='Usuario que crea')),
                ('fecha_crea', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('usuario_modifica', models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', max_length=50, verbose_name='Último usuario que modifica')),
                ('fecha_modifica', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
            ],
            options={
                'verbose_name': 'Parámetro Tributario',
                'verbose_name_plural': 'Parámetros Tributarios',
                'db_table': 'parametros_tributarios',
                'ordering': ['-ano_vigencia', 'tipo_parametro', 'empresa'],
            },
        ),
        migrations.CreateModel(
            name='TipoCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_collation='latin1_swedish_ci', max_length=1, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(db_collation='latin1_swedish_ci', max_length=50, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Categoría',
                'verbose_name_plural': 'Tipos de Categoría',
                'db_table': 'tipocategoria',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionesIcs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('idneg', models.IntegerField(default=0, verbose_name='ID Negocio')),
                ('nodeclara', models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', max_length=20, verbose_name='No. Declaración')),
                ('empresa', models.CharField(blank=True, db_collation='latin1_swedish_ci', default=None, max_length=4, null=True, verbose_name='Empresa')),
                ('rtm', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=16, verbose_name='RTM')),
                ('expe', models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', max_length=12, verbose_name='Expediente')),
                ('ano', models.DecimalField(decimal_places=0, default=0, max_digits=4, verbose_name='Año')),
                ('mes', models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', max_length=2, verbose_name='Mes')),
                ('operacion', models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', max_length=1, verbose_name='Operación')),
                ('rubro', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=6, verbose_name='Rubro')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto')),
                ('tasa', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Tasa')),
                ('usuario', models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', max_length=50, verbose_name='Usuario')),
                ('fechasys', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Sistema')),
            ],
            options={
                'verbose_name': 'Transacción ICS',
                'verbose_name_plural': 'Transacciones ICS',
                'db_table': 'transaccionesics',
            },
        ),
        migrations.AlterUniqueTogether(
            name='planarbitrio',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='declaracionvolumen',
            name='valor_base',
        ),
        migrations.RemoveField(
            model_name='negocio',
            name='categoria',
        ),
        migrations.AddField(
            model_name='actividad',
            name='cuentaint',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=20, verbose_name='Cuenta Intereses'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='cuentarec',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=20, verbose_name='Cuenta Recargos'),
        ),
        migrations.AddField(
            model_name='norecibos',
            name='empresa',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', default=None, max_length=6, null=True, verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='pagovariostemp',
            name='rubro',
            field=models.CharField(blank=True, db_collation='latin1_swedish_ci', default='', max_length=6, verbose_name='Rubro'),
        ),
        migrations.AddField(
            model_name='planarbitrio',
            name='tipocat',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=1, verbose_name='Tipo de Categoría'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='codigo',
            field=models.CharField(db_collation='utf8mb4_0900_ai_ci', default='', max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='cuentarez',
            field=models.CharField(db_collation='utf8mb4_0900_ai_ci', default='', max_length=20, verbose_name='Cuenta Rezago'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.CharField(blank=True, db_collation='utf8mb4_0900_ai_ci', default='', max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='empresa',
            field=models.CharField(db_collation='utf8mb4_0900_ai_ci', default='', max_length=4, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='catastral',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=17, verbose_name='Catastral'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='comentario',
            field=models.TextField(blank=True, db_collation='latin1_swedish_ci', null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='cx',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Coordenada X (UTM)'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='cy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Coordenada Y (UTM)'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='empresa',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=4, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='estatus',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=1, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='expe',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=12, verbose_name='Expediente'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='identidad',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=20, verbose_name='Identidad'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='rtm',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=16, verbose_name='RTM'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='socios',
            field=models.CharField(db_collation='latin1_swedish_ci', max_length=250, verbose_name='Socios'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='expe',
            field=models.CharField(db_collation='latin1_swedish_ci', default='0', max_length=12, verbose_name='Expediente'),
        ),
        migrations.AlterUniqueTogether(
            name='planarbitrio',
            unique_together={('empresa', 'rubro', 'cod_tarifa', 'tipocat', 'ano', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='planarbitrio',
            index=models.Index(fields=['empresa'], name='planarbitio_idx2'),
        ),
        migrations.AddIndex(
            model_name='planarbitrio',
            index=models.Index(fields=['rubro'], name='planarbitio_idx3'),
        ),
        migrations.AddIndex(
            model_name='planarbitrio',
            index=models.Index(fields=['cod_tarifa'], name='planarbitio_idx4'),
        ),
        migrations.AddIndex(
            model_name='planarbitrio',
            index=models.Index(fields=['ano'], name='planarbitio_idx5'),
        ),
        migrations.AddIndex(
            model_name='planarbitrio',
            index=models.Index(fields=['codigo'], name='planarbitio_idx6'),
        ),
        migrations.AddIndex(
            model_name='planarbitrio',
            index=models.Index(fields=['tipocat'], name='planarbitio_idx7'),
        ),
        migrations.AddIndex(
            model_name='transaccionesics',
            index=models.Index(fields=['rtm'], name='transaccionesics_idx1'),
        ),
        migrations.AddIndex(
            model_name='transaccionesics',
            index=models.Index(fields=['expe'], name='transaccionesics_idx2'),
        ),
        migrations.AddIndex(
            model_name='transaccionesics',
            index=models.Index(fields=['rubro'], name='transaccionesics_idx3'),
        ),
        migrations.AddIndex(
            model_name='transaccionesics',
            index=models.Index(fields=['fecha'], name='transaccionesics_idx4'),
        ),
        migrations.AddIndex(
            model_name='transaccionesics',
            index=models.Index(fields=['idneg'], name='transaccionesics_idx5'),
        ),
        migrations.AddIndex(
            model_name='transaccionesics',
            index=models.Index(fields=['empresa'], name='transaccionesics_idx6'),
        ),
        migrations.AddConstraint(
            model_name='transaccionesics',
            constraint=models.UniqueConstraint(fields=('empresa', 'rtm', 'expe', 'ano', 'mes', 'rubro'), name='transaccionesics_idx7'),
        ),
        migrations.AddConstraint(
            model_name='tipocategoria',
            constraint=models.UniqueConstraint(fields=('codigo',), name='codigo_new'),
        ),
        migrations.AddIndex(
            model_name='parametrostributarios',
            index=models.Index(fields=['empresa', 'tipo_parametro', 'ano_vigencia'], name='idx_paramtrib_emp_tipo_ano'),
        ),
        migrations.AddIndex(
            model_name='parametrostributarios',
            index=models.Index(fields=['activo'], name='idx_paramtrib_activo'),
        ),
    ]
