# Generated by Django 4.2.27 on 2026-04-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0051_add_parametros_tributarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
