# Generated by Django 4.2.27 on 2026-04-30 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0057_fix_pagovariostemp_id_autoincrement_postgres'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoOperacionRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Año')),
                ('bomberos', models.BooleanField(default=False, verbose_name='Cuerpo de Bomberos')),
                ('salud', models.BooleanField(default=False, verbose_name='Salud Pública')),
                ('ambiente', models.BooleanField(default=False, verbose_name='Ambiente')),
                ('otros', models.BooleanField(default=False, verbose_name='Otros')),
                ('usuario', models.CharField(blank=True, max_length=50, verbose_name='Usuario verificador')),
                ('fecha_verificacion', models.DateTimeField(auto_now=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_permiso', to='tributario_app.negocio')),
            ],
            options={
                'verbose_name': 'Requisito de Permiso',
                'verbose_name_plural': 'Requisitos de Permisos',
                'db_table': 'permiso_operacion_requisito',
                'unique_together': {('negocio', 'ano')},
            },
        ),
    ]
