# Generated by Django 4.2.30 on 2026-04-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario_app', '0059_fix_db_compatibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='codigo',
            field=models.CharField(default='', max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='cuentaint',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cuenta Intereses'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='cuentarec',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cuenta Recargos'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='cuentarez',
            field=models.CharField(default='', max_length=20, verbose_name='Cuenta Rezago'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='empresa',
            field=models.CharField(default='', max_length=4, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='anoemprenu',
            name='empresa',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='empresa',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='expe',
            field=models.CharField(default='', max_length=10, verbose_name='Expediente'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='nodecla',
            field=models.CharField(default='', max_length=20, verbose_name='Número de Declaración'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='rtm',
            field=models.CharField(default='', max_length=20, verbose_name='RTM'),
        ),
        migrations.AlterField(
            model_name='declaracionvolumen',
            name='usuario',
            field=models.CharField(default='', max_length=50, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='apellidos',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='identidad',
            field=models.CharField(max_length=18, unique=True, verbose_name='Identidad'),
        ),
        migrations.AlterField(
            model_name='identificacion',
            name='nombres',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='actividad',
            field=models.CharField(default=' ', max_length=20, verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='catastral',
            field=models.CharField(max_length=17, verbose_name='Catastral'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='celular',
            field=models.CharField(default=' ', max_length=20, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='comentario',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='comerciante',
            field=models.CharField(default=' ', max_length=100, verbose_name='Comerciante'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='correo',
            field=models.CharField(default=' ', max_length=35, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='descriactividad',
            field=models.CharField(default=' ', max_length=100, verbose_name='Descripción Actividad'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='descriestatus',
            field=models.CharField(default=' ', max_length=50, verbose_name='Descripción Estatus'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='direccion',
            field=models.CharField(default=' ', max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='empresa',
            field=models.CharField(max_length=4, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='estatus',
            field=models.CharField(max_length=1, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='expe',
            field=models.CharField(max_length=12, verbose_name='Expediente'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='identidad',
            field=models.CharField(max_length=20, verbose_name='Identidad'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='identidadrep',
            field=models.CharField(default=' ', max_length=20, verbose_name='Identidad Representante'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='nombrenego',
            field=models.CharField(default=' ', max_length=100, verbose_name='Nombre Negocio'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='pagweb',
            field=models.CharField(default=' ', max_length=40, verbose_name='Página Web'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='representante',
            field=models.CharField(default=' ', max_length=100, verbose_name='Representante'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='rtm',
            field=models.CharField(max_length=16, verbose_name='RTM'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='rtnnego',
            field=models.CharField(default=' ', max_length=19, verbose_name='RTN Negocio'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='rtnpersonal',
            field=models.CharField(default=' ', max_length=20, verbose_name='RTN Personal'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='socios',
            field=models.CharField(max_length=250, verbose_name='Socios'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='telefono',
            field=models.CharField(default=' ', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='usuario',
            field=models.CharField(default=' ', max_length=10, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='norecibos',
            name='empresa',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='oficina',
            name='empresa',
            field=models.CharField(max_length=4, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='Rtm',
            field=models.CharField(default=' ', max_length=20, verbose_name='RTM'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='Tipofa',
            field=models.CharField(default=' ', max_length=1, verbose_name='Tipo de Factura'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='aplicado',
            field=models.CharField(default='0', max_length=1, verbose_name='Aplicado'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='banco',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='cajero',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cajero'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='categoria',
            field=models.CharField(default='', max_length=2, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='codigo',
            field=models.CharField(max_length=16, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='comentario',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='direccion',
            field=models.CharField(default=' ', max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='empresa',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='expe',
            field=models.CharField(default='0', max_length=12, verbose_name='Expediente'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='facturadora',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Facturadora'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='identidad',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='Identidad'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='oficina',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='prima',
            field=models.CharField(default='', max_length=1, verbose_name='Prima'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='referencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='rtn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RTN'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='rubro',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='Rubro'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='sexo',
            field=models.CharField(default='', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='traslado',
            field=models.CharField(default='0', max_length=1, verbose_name='Traslado'),
        ),
        migrations.AlterField(
            model_name='pagovariostemp',
            name='usuario',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='cod_tarifa',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Código de Tarifa'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='codigo',
            field=models.CharField(default='', max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='empresa',
            field=models.CharField(default='', max_length=4, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='rubro',
            field=models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Rubro'),
        ),
        migrations.AlterField(
            model_name='planarbitrio',
            name='tipocat',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='Tipo de Categoría'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='codigo',
            field=models.CharField(default='', max_length=6, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='cuenta',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='cuentarez',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cuenta Rezago'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='empresa',
            field=models.CharField(default='', max_length=4, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='rubromoratorioconfig',
            name='empresa',
            field=models.CharField(default='', max_length=4, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='rubromoratorioconfig',
            name='rubro_codigo',
            field=models.CharField(default='', max_length=6, verbose_name='Rubro Moratorio'),
        ),
        migrations.AlterField(
            model_name='rubromoratorioconfig',
            name='rubro_padre_codigo',
            field=models.CharField(default='', max_length=6, verbose_name='Rubro Padre'),
        ),
        migrations.AlterField(
            model_name='rubromoratorioconfig',
            name='usuario_crea',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Usuario crea'),
        ),
        migrations.AlterField(
            model_name='rubromoratorioconfig',
            name='usuario_modifica',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Usuario modifica'),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='cod_tarifa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de Tarifa'),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='empresa',
            field=models.CharField(default='', max_length=4, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='frecuencia',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Frecuencia'),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='rubro',
            field=models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Rubro'),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='tipo',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tarifas',
            name='tipomodulo',
            field=models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Tipo Módulo'),
        ),
        migrations.AlterField(
            model_name='tarifasics',
            name='cod_tarifa',
            field=models.CharField(blank=True, default='', max_length=4, null=True, verbose_name='Código de Tarifa'),
        ),
        migrations.AlterField(
            model_name='tarifasics',
            name='cuenta',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='tarifasics',
            name='cuentarez',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Cuenta Rezago'),
        ),
        migrations.AlterField(
            model_name='tarifasics',
            name='empresa',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tarifasics',
            name='expe',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Expediente'),
        ),
        migrations.AlterField(
            model_name='tarifasics',
            name='rtm',
            field=models.CharField(default='', max_length=20, verbose_name='RTM'),
        ),
        migrations.AlterField(
            model_name='tarifasics',
            name='rubro',
            field=models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Rubro'),
        ),
        migrations.AlterField(
            model_name='tarifasimptoics',
            name='categoria',
            field=models.CharField(blank=True, default='', max_length=1, null=True, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='tarifasimptoics',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tasasdecla',
            name='cod_tarifa',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Código de Tarifa'),
        ),
        migrations.AlterField(
            model_name='tasasdecla',
            name='cuenta',
            field=models.CharField(default='', max_length=20, verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='tasasdecla',
            name='cuentarez',
            field=models.CharField(default='', max_length=20, verbose_name='Cuenta Rezago'),
        ),
        migrations.AlterField(
            model_name='tasasdecla',
            name='empresa',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='tasasdecla',
            name='expe',
            field=models.CharField(default='', max_length=10, verbose_name='Expediente'),
        ),
        migrations.AlterField(
            model_name='tasasdecla',
            name='frecuencia',
            field=models.CharField(default='', max_length=1, verbose_name='Frecuencia'),
        ),
        migrations.AlterField(
            model_name='tasasdecla',
            name='nodecla',
            field=models.CharField(default='', max_length=20, verbose_name='Número de Declaración'),
        ),
        migrations.AlterField(
            model_name='tasasdecla',
            name='rtm',
            field=models.CharField(default='', max_length=20, verbose_name='RTM'),
        ),
        migrations.AlterField(
            model_name='tasasdecla',
            name='rubro',
            field=models.CharField(default='', max_length=6, verbose_name='Rubro'),
        ),
        migrations.AlterField(
            model_name='tasasdecla',
            name='tipota',
            field=models.CharField(db_column='tipota', default='', max_length=1, verbose_name='Tipo Tasa'),
        ),
        migrations.AlterField(
            model_name='tipocategoria',
            name='codigo',
            field=models.CharField(max_length=1, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='tipocategoria',
            name='descripcion',
            field=models.CharField(max_length=50, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='transaccionesics',
            name='empresa',
            field=models.CharField(blank=True, default=None, max_length=4, null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='transaccionesics',
            name='expe',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Expediente'),
        ),
        migrations.AlterField(
            model_name='transaccionesics',
            name='mes',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='transaccionesics',
            name='nodeclara',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='No. Declaración'),
        ),
        migrations.AlterField(
            model_name='transaccionesics',
            name='operacion',
            field=models.CharField(blank=True, default='', max_length=1, verbose_name='Operación'),
        ),
        migrations.AlterField(
            model_name='transaccionesics',
            name='rtm',
            field=models.CharField(default='', max_length=16, verbose_name='RTM'),
        ),
        migrations.AlterField(
            model_name='transaccionesics',
            name='rubro',
            field=models.CharField(default='', max_length=6, verbose_name='Rubro'),
        ),
        migrations.AlterField(
            model_name='transaccionesics',
            name='usuario',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Usuario'),
        ),
        # migrations.CreateModel(
        #     name='TransaccionesBienesInmuebles',
        #     fields=[
        #         ('id', models.AutoField(primary_key=True, serialize=False)),
        #         ('empresa', models.CharField(blank=True, max_length=4, null=True, verbose_name='Empresa')),
        #         ('cocata1', models.CharField(default='', max_length=20, verbose_name='Clave Catastral')),
        #         ('rubro', models.CharField(max_length=6, verbose_name='Rubro')),
        #         ('ano', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Año')),
        #         ('mes', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Mes')),
        #         ('operacion', models.CharField(default='F', max_length=1, verbose_name='Operación')),
        #         ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto')),
        #         ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
        #         ('vencimiento', models.DateField(blank=True, null=True, verbose_name='Vencimiento')),
        #         ('usuario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario')),
        #         ('fechasys', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Sistema')),
        #         ('estado', models.CharField(default='A', max_length=1, verbose_name='Estado')),
        #     ],
        #     options={
        #         'verbose_name': 'Transacción Bienes Inmuebles',
        #         'verbose_name_plural': 'Transacciones Bienes Inmuebles',
        #         'db_table': 'transaccionesbienesinmuebles',
        #         'ordering': ['-ano', '-mes', 'fecha'],
        #         'indexes': [models.Index(fields=['empresa', 'cocata1'], name='idx_transbienes_emp_cocata'), models.Index(fields=['empresa', 'cocata1', 'ano', 'mes', 'rubro'], name='idx_transbienes_unique')],
        #     },
        # ),
    ]
