# Generated by Django 5.2.1 on 2025-08-26 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='updated_at',
        ),
    ]
