# Generated by Django 5.2.1 on 2025-10-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_municipio_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=3, verbose_name='Código')),
                ('descripcion', models.CharField(db_collation='latin1_swedish_ci', default='', max_length=29, verbose_name='Descripción')),
                ('departamento_field1', models.IntegerField(blank=True, null=True, verbose_name='Campo Adicional')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='departament_codigo_d7e7cf_idx')],
                'unique_together': {('codigo',)},
            },
        ),
    ]
