# Generated by Django 4.2.27 on 2026-04-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_departamento_id_depto_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipio',
            options={'managed': False, 'ordering': ['codigo'], 'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
    ]
