# Generated by Django 4.2.30 on 2026-04-30 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_municipio_campos_extendidos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='municipio',
            table='municipio',
        ),
    ]
