# Generated by Django 5.2+ (manual migration for tesoreria)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.CharField(max_length=10, verbose_name='Empresa/Municipio')),
                ('tipo', models.CharField(choices=[('CAJA_GENERAL', 'Caja General'), ('BANCO', 'Banco'), ('CHEQUERA', 'Cuenta de Cheques / Chequera')], max_length=20, verbose_name='Tipo')),
                ('codigo', models.CharField(max_length=30, verbose_name='Código')),
                ('nombre', models.CharField(blank=True, null=True, max_length=200, verbose_name='Nombre')),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tesoreria_cuentas', to='contabilidad.cuentacontable', verbose_name='Cuenta contable (catálogo contable)')),
            ],
            options={
                'db_table': 'teso_cuenta_tesoreria',
                'verbose_name': 'Cuenta de Tesorería',
                'verbose_name_plural': 'Cuentas de Tesorería',
                'ordering': ['tipo', 'codigo'],
                'unique_together': {('empresa', 'tipo', 'codigo')},
            },
        ),
    ]

