# Generated by Django 4.2.27 on 2026-03-22 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0005_alter_ordenpago_estado'),
        ('tesoreria', '0002_cheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoDetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Aplicado')),
                ('orden_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_tesoreria', to='presupuestos.ordenpago')),
            ],
            options={
                'verbose_name': 'Detalle de Pago (Orden)',
                'verbose_name_plural': 'Detalles de Pago (Órdenes)',
                'db_table': 'teso_pago_detalle_orden',
            },
        ),
        migrations.CreateModel(
            name='PagoTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.CharField(max_length=10, verbose_name='Empresa/Municipio')),
                ('tipo_pago', models.CharField(choices=[('CHEQUE', 'Cheque'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('EFECTIVO', 'Efectivo/Caja')], default='CHEQUE', max_length=20)),
                ('numero_referencia', models.CharField(max_length=50, verbose_name='No. Cheque / Referencia')),
                ('fecha', models.DateField(verbose_name='Fecha de Pago')),
                ('beneficiario', models.CharField(max_length=200, verbose_name='Beneficiario / Páguese a')),
                ('concepto', models.TextField(blank=True, null=True, verbose_name='Concepto del Pago')),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Monto Total')),
                ('estado', models.CharField(choices=[('EMITIDO', 'Emitido/Pendiente'), ('PAGADO', 'Pagado/Efectuado'), ('ANULADO', 'Anulado')], default='EMITIDO', max_length=15)),
                ('punto_acta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Punto de Acta / Respaldo')),
                ('cuenta_tesoreria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='tesoreria.cuentatesoreria', verbose_name='Cuenta Origen')),
            ],
            options={
                'verbose_name': 'Pago de Tesorería',
                'verbose_name_plural': 'Pagos de Tesorería',
                'db_table': 'teso_pago',
                'ordering': ['-fecha', '-numero_referencia'],
                'unique_together': {('empresa', 'numero_referencia', 'tipo_pago')},
            },
        ),
        migrations.DeleteModel(
            name='Cheque',
        ),
        migrations.AddField(
            model_name='pagodetalleorden',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_ordenes', to='tesoreria.pagotesoreria'),
        ),
    ]
