# Generated by Django 4.2.27 on 2026-03-22 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0007_operacionmanual_delete_gastomanual'),
        ('tesoreria', '0003_pagodetalleorden_pagotesoreria_delete_cheque_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.CharField(max_length=10)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('saldo_banco', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldo_libro', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador/En Proceso'), ('FINALIZADA', 'Finalizada')], default='BORRADOR', max_length=15)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('cuenta_tesoreria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cuentatesoreria')),
            ],
            options={
                'db_table': 'teso_conciliacion',
                'unique_together': {('empresa', 'cuenta_tesoreria', 'anio', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='DepositoTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('numero_referencia', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('concepto', models.TextField(blank=True, null=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('cuenta_tesoreria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depositos', to='tesoreria.cuentatesoreria')),
            ],
            options={
                'db_table': 'teso_deposito',
                'unique_together': {('empresa', 'numero_referencia')},
            },
        ),
        migrations.AlterModelOptions(
            name='pagodetalleorden',
            options={},
        ),
        migrations.AddField(
            model_name='pagotesoreria',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega'),
        ),
        migrations.AddField(
            model_name='pagotesoreria',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='Entregado'),
        ),
        migrations.CreateModel(
            name='NotaTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.CharField(max_length=10)),
                ('tipo', models.CharField(choices=[('CREDITO', 'Nota de Crédito'), ('DEBITO', 'Nota de Débito')], max_length=10)),
                ('fecha', models.DateField()),
                ('numero_referencia', models.CharField(max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('concepto', models.TextField(blank=True, null=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('cuenta_tesoreria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='tesoreria.cuentatesoreria')),
                ('orden_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_debito', to='presupuestos.ordenpago')),
            ],
            options={
                'db_table': 'teso_nota',
                'unique_together': {('empresa', 'tipo', 'numero_referencia')},
            },
        ),
        migrations.CreateModel(
            name='DetalleConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_banco', models.DateField()),
                ('conciliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tesoreria.conciliacionbancaria')),
                ('deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesoreria.depositotesoreria')),
                ('nota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesoreria.notatesoreria')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesoreria.pagotesoreria')),
            ],
            options={
                'db_table': 'teso_conciliacion_detalle',
            },
        ),
    ]
