# Generated by Django 4.2.27 on 2026-04-01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tesoreria", "0004_conciliacionbancaria_depositotesoreria_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CobroCaja",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("empresa", models.CharField(max_length=10, verbose_name="Empresa/Municipio")),
                ("fecha", models.DateField(verbose_name="Fecha de Cobro")),
                ("cajero", models.CharField(blank=True, max_length=50, null=True, verbose_name="Cajero")),
                ("total_cobrado", models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Total Cobrado")),
                ("fuente", models.CharField(choices=[("CAJA", "Caja"), ("WEBSERVICE", "Webservice")], default="CAJA", max_length=15, verbose_name="Fuente")),
                ("recibos_json", models.TextField(blank=True, null=True, verbose_name="Recibos incluidos (JSON)")),
                ("referencia", models.CharField(blank=True, max_length=80, null=True, verbose_name="Referencia")),
                ("observacion", models.TextField(blank=True, null=True, verbose_name="Observación")),
            ],
            options={
                "verbose_name": "Cobro en Caja",
                "verbose_name_plural": "Cobros en Caja",
                "db_table": "teso_cobro_caja",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CobroCajaMetodo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización")),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                ("forma_pago", models.CharField(choices=[("EFECTIVO", "Efectivo"), ("POS", "POS"), ("CHEQUE", "Cheque"), ("COMPENSACION", "Compensación")], default="EFECTIVO", max_length=20, verbose_name="Forma de Pago")),
                ("monto", models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name="Monto")),
                ("referencia", models.CharField(blank=True, max_length=80, null=True, verbose_name="Referencia/Documento")),
                ("cobro", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="metodos", to="tesoreria.cobrocaja")),
            ],
            options={
                "verbose_name": "Detalle de Forma de Pago",
                "verbose_name_plural": "Detalles de Formas de Pago",
                "db_table": "teso_cobro_caja_metodo",
                "ordering": ["id"],
            },
        ),
    ]
