# Generated by Django 5.2.1 on 2025-10-03 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('identidad', models.CharField(max_length=31, unique=True, verbose_name='Identidad')),
                ('nombres', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Identificación',
                'verbose_name_plural': 'Identificaciones',
                'db_table': 'mod_tributario_identificacion',
            },
        ),
        migrations.CreateModel(
            name='PagoVariosTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.CharField(max_length=4, verbose_name='Empresa')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Pago Varios Temporal',
                'verbose_name_plural': 'Pagos Varios Temporales',
                'db_table': 'pago_varios_temp',
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.CharField(max_length=4, verbose_name='Empresa')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'mod_tributario_actividad',
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empre', models.CharField(max_length=4, verbose_name='Empresa')),
                ('rtm', models.CharField(max_length=20, verbose_name='RTM')),
                ('expe', models.CharField(max_length=20, verbose_name='Expediente')),
                ('fecha_ini', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('fecha_can', models.DateField(blank=True, null=True, verbose_name='Fecha Cancelación')),
                ('identidad', models.CharField(blank=True, max_length=15, null=True, verbose_name='Identidad')),
                ('rtnpersonal', models.CharField(blank=True, max_length=14, null=True, verbose_name='RTN Personal')),
                ('comerciante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comerciante')),
                ('rtnnego', models.CharField(blank=True, max_length=14, null=True, verbose_name='RTN Negocio')),
                ('nombrenego', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Negocio')),
                ('actividad', models.CharField(blank=True, max_length=20, null=True, verbose_name='Actividad')),
                ('identidadrep', models.CharField(blank=True, max_length=15, null=True, verbose_name='Identidad Representante')),
                ('representante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Representante')),
                ('estatus', models.CharField(default='A', max_length=1, verbose_name='Estatus')),
                ('catastral', models.CharField(blank=True, max_length=20, null=True, verbose_name='Catastral')),
                ('cx', models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Coordenada X')),
                ('cy', models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='Coordenada Y')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=9, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('correo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo')),
                ('pagweb', models.CharField(blank=True, max_length=100, null=True, verbose_name='Página Web')),
                ('socios', models.CharField(blank=True, max_length=200, null=True, verbose_name='Socios')),
                ('comentario', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comentario')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'db_table': 'negocio',
                'unique_together': {('empre', 'rtm', 'expe')},
            },
        ),
        migrations.CreateModel(
            name='NoRecibos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.CharField(max_length=4, verbose_name='Empresa')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('tipo', models.CharField(max_length=20, verbose_name='Tipo')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Número de Recibo',
                'verbose_name_plural': 'Números de Recibos',
                'db_table': 'no_recibos',
                'unique_together': {('empresa', 'numero', 'tipo')},
            },
        ),
    ]
