# Generated by Django 5.2.1 on 2025-10-18 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tributario', '0001_initial'),
    ]

    operations = [
        # Crear tabla anoemprenu solo si no existe
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS `anoemprenu` (
                  `id` INTEGER NOT NULL AUTO_INCREMENT,
                  `empresa` CHAR(6) COLLATE latin1_swedish_ci DEFAULT NULL,
                  `ano` DECIMAL(4,0) DEFAULT NULL,
                  `nopermiso` DECIMAL(12,0) DEFAULT NULL,
                  `noplanes` DECIMAL(12,0) DEFAULT 0,
                  PRIMARY KEY USING BTREE (`id`)
                ) ENGINE=MyISAM AUTO_INCREMENT=1 ROW_FORMAT=FIXED 
                  CHARACTER SET 'latin1' COLLATE 'latin1_swedish_ci';
            """,
            reverse_sql="DROP TABLE IF EXISTS `anoemprenu`;"
        ),
        # Agregar campo nodecla a la tabla declara solo si no existe
        migrations.RunSQL(
            sql="""
                SET @col_exists = 0;
                SELECT COUNT(*) INTO @col_exists 
                FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                  AND TABLE_NAME = 'declara' 
                  AND COLUMN_NAME = 'nodecla';

                SET @sql = IF(@col_exists = 0,
                    "ALTER TABLE `declara` ADD COLUMN `nodecla` CHAR(20) COLLATE latin1_swedish_ci DEFAULT '' AFTER `id`",
                    "SELECT 'Column nodecla already exists' AS message");
                    
                PREPARE stmt FROM @sql;
                EXECUTE stmt;
                DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="""
                ALTER TABLE `declara` DROP COLUMN IF EXISTS `nodecla`;
            """
        ),
    ]
